import TypeIIITorsionCoefficientCoordinates
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# The actual finite quotients of the coefficient limit

The original projection to level n is surjective.  Its kernel is exactly
the ideal generated by ℓ^(n+1), as follows by dividing each actual ℓ-adic
coordinate.  The resulting quotient-ring equivalence sends the class of
an element to its original finite projection.

Only primality of p and ℓ is needed here; they need not be distinct.
No product-ring decomposition, local-factor selection, or cohomology
statement is asserted.
-/

noncomputable section

namespace PrimeGap182.TypeIII

open scoped Classical

/-- Lifting the integer representatives of the finite basis coordinates
gives a preimage under the original projection. -/
theorem torsionCoefficientLimitProjection_surjective (p ell n : ℕ)
    [Fact p.Prime] [Fact ell.Prime] :
    Function.Surjective (torsionCoefficientLimitProjection p ell n) := by
  intro x
  let v : Fin (p - 1) → ℤ_[ell] :=
    fun i => ((torsionCoefficientBasis p ell n).equivFun x i).val
  refine ⟨torsionCoefficientLimitCombination p ell v, ?_⟩
  apply (torsionCoefficientBasis p ell n).equivFun.injective
  funext i
  rw [torsionCoefficientLimitCombination_coordinates]
  simp only [v, map_natCast, ZMod.natCast_zmod_val]

/-- The displayed power of ℓ vanishes under the actual level-n projection. -/
@[simp] theorem torsionCoefficientLimitProjection_ell_pow (p ell n : ℕ)
    [Fact p.Prime] [Fact ell.Prime] :
    torsionCoefficientLimitProjection p ell n
      ((ell : TorsionCoefficientLimit p ell) ^ (n + 1)) = 0 := by
  rw [map_pow, map_natCast, ← Nat.cast_pow]
  exact CharP.cast_eq_zero (TorsionCoefficientRing p ell n) (ell ^ (n + 1))

/-- Vanishing at the actual finite level is divisibility by the
displayed power of ℓ in the existing limit ring. -/
theorem torsionCoefficientLimitProjection_eq_zero_iff (p ell n : ℕ)
    [Fact p.Prime] [Fact ell.Prime] (x : TorsionCoefficientLimit p ell) :
    torsionCoefficientLimitProjection p ell n x = 0 ↔
      (ell : TorsionCoefficientLimit p ell) ^ (n + 1) ∣ x := by
  constructor
  · intro hx
    have hcoords : ∀ i : Fin (p - 1),
        (ell : ℤ_[ell]) ^ (n + 1) ∣ torsionCoefficientLimitEquivFun p ell x i := by
      intro i
      apply Ideal.mem_span_singleton.mp
      rw [← PadicInt.ker_toZModPow]
      apply RingHom.mem_ker.mpr
      simp only [torsionCoefficientLimitEquivFun_projection, hx, map_zero, Pi.zero_apply]
    choose v hv using hcoords
    refine ⟨torsionCoefficientLimitCombination p ell v, ?_⟩
    calc
      x = torsionCoefficientLimitCombination p ell (torsionCoefficientLimitEquivFun p ell x) := by
        rw [← torsionCoefficientLimitEquivFun_symm_apply, LinearEquiv.symm_apply_apply]
      _ = torsionCoefficientLimitCombination p ell ((ell : ℤ_[ell]) ^ (n + 1) • v) := by
        congr 1
        funext i
        exact hv i
      _ = (ell : ℤ_[ell]) ^ (n + 1) • torsionCoefficientLimitCombination p ell v :=
        map_smul (torsionCoefficientLimitCombination p ell) _ _
      _ = (ell : TorsionCoefficientLimit p ell) ^ (n + 1) *
          torsionCoefficientLimitCombination p ell v := by
        simp only [Algebra.smul_def, map_pow, map_natCast]
  · rintro ⟨y, rfl⟩
    rw [map_mul, torsionCoefficientLimitProjection_ell_pow, zero_mul]

/-- The kernel of the unchanged projection is exactly the principal ℓ-power ideal. -/
theorem torsionCoefficientLimitProjection_ker (p ell n : ℕ)
    [Fact p.Prime] [Fact ell.Prime] :
    RingHom.ker (torsionCoefficientLimitProjection p ell n) =
      Ideal.span {(ell : TorsionCoefficientLimit p ell) ^ (n + 1)} := by
  ext x
  rw [RingHom.mem_ker, Ideal.mem_span_singleton, torsionCoefficientLimitProjection_eq_zero_iff]

/-- The canonical quotient identification induced by the original projection. -/
def torsionCoefficientLimitQuotientEquiv (p ell n : ℕ) [Fact p.Prime] [Fact ell.Prime] :
    TorsionCoefficientLimit p ell ⧸
        Ideal.span {(ell : TorsionCoefficientLimit p ell) ^ (n + 1)} ≃+*
      TorsionCoefficientRing p ell n :=
  (Ideal.quotEquivOfEq (torsionCoefficientLimitProjection_ker p ell n).symm).trans
    (RingHom.quotientKerEquivOfSurjective (torsionCoefficientLimitProjection_surjective p ell n))

/-- On every class, the equivalence is literally the original finite projection. -/
@[simp] theorem torsionCoefficientLimitQuotientEquiv_mk (p ell n : ℕ)
    [Fact p.Prime] [Fact ell.Prime] (x : TorsionCoefficientLimit p ell) :
    torsionCoefficientLimitQuotientEquiv p ell n
      (Ideal.Quotient.mk (Ideal.span {(ell : TorsionCoefficientLimit p ell) ^ (n + 1)}) x) =
      torsionCoefficientLimitProjection p ell n x := by
  simp only [torsionCoefficientLimitQuotientEquiv, RingEquiv.trans_apply,
    Ideal.quotEquivOfEq_mk, RingHom.quotientKerEquivOfSurjective_apply_mk]

/-- The canonical quotient square commutes as an equality of actual ring homomorphisms. -/
theorem torsionCoefficientLimitQuotientEquiv_comp_mk (p ell n : ℕ)
    [Fact p.Prime] [Fact ell.Prime] :
    (torsionCoefficientLimitQuotientEquiv p ell n).toRingHom.comp
        (Ideal.Quotient.mk (Ideal.span {(ell : TorsionCoefficientLimit p ell) ^ (n + 1)})) =
      torsionCoefficientLimitProjection p ell n := by
  apply RingHom.ext
  intro x
  exact torsionCoefficientLimitQuotientEquiv_mk p ell n x

#print axioms torsionCoefficientLimitProjection_surjective
#print axioms torsionCoefficientLimitProjection_ell_pow
#print axioms torsionCoefficientLimitProjection_eq_zero_iff
#print axioms torsionCoefficientLimitProjection_ker
#print axioms torsionCoefficientLimitQuotientEquiv
#print axioms torsionCoefficientLimitQuotientEquiv_mk
#print axioms torsionCoefficientLimitQuotientEquiv_comp_mk

end PrimeGap182.TypeIII
