import TypeIIICappedNormalization

/-!
# The actual nonzero Fourier estimate with the new Type III cutoff

The exact CRT, signed frequency partition, and complete-fiber reduction are
ported from the hash-pinned public 186 baseline. The old analytic Kloosterman
estimate is replaced by the checked five-term estimate with capped selection.
Generated by scripts/build_type_iii_nonzero_fourier.py.
-/

open scoped BigOperators Classical ContDiff NNReal
open PrimeGap186 PrimeGap182Audit UniqueFactorizationMonoid

namespace PrimeGap182.TypeIII

noncomputable section

set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option maxHeartbeats 3000000

theorem LocalFourierHypothesis.fineBand_nonzero_fourier_power_saving
    {C₀ : ℝ} (hC₀ : 0 ≤ C₀) {D₀ p₀ : ℕ} (hlocal : LocalFourierHypothesis C₀ D₀ p₀)
    (omegaExp δ σ C : ℝ)
    (hω : 0 < omegaExp) (hδ : 0 < δ) (hC : 1 ≤ C) (hσupper : σ < 1 / 6)
    (hσ : 1 / 30 + 56 * omegaExp / 15 + 4 * δ / 15 < σ)
    (hswitch : 1 < 108 * omegaExp + 2 * δ) :
    let μ : ℝ := typeIIIMu σ
    let θ : ℝ := typeIIITheta omegaExp
    let εcap : ℝ := typeIIIEpsilonCap μ θ δ
    0 < εcap ∧
      ∀ ε : ℝ, 0 < ε → ε ≤ εcap →
      ∃ K X : ℝ, 0 < K ∧ 1 ≤ X ∧
      ∀ x : ℝ, X ≤ x →
      ∀ M N₁ N₂ N₃ Qcenter : ℝ,
        1 ≤ M → 1 ≤ N₁ → 1 ≤ N₂ → 1 ≤ N₃ → 0 < Qcenter →
        let N : ℝ := N₁ * N₂ * N₃
        x / C ≤ M * N → M * N ≤ C * x →
        x ^ (3 / 4 + 3 * σ / 2 - ε) / C ≤ N →
        Qcenter ≤ C * x ^ (1 / 2 + 2 * omegaExp + ε) →
      ∀ Y : Set.Ici (1 : ℝ), (Y : ℝ) = x ^ δ →
      ∀ Qset : Finset ℕ+,
        (∀ q ∈ Qset,
          Squarefree (q : ℕ) ∧
          Nonempty (DenseDivisibilityWitness Y 1 (q : ℕ)) ∧
          Qcenter * (1 - C * x ^ (-ε)) ≤ (q : ℝ) ∧
          (q : ℝ) ≤ Qcenter * (1 + C * x ^ (-ε))) →
      ∀ (a₀ : ℤ) (a : ∀ q : ℕ+, (ZMod (q : ℕ))ˣ),
        (∀ q ∈ Qset, (a q : ZMod (q : ℕ)) = (a₀ : ZMod (q : ℕ))) →
      ∀ M₀ M₁ : ℤ, 0 < M₀ → (M₁ : ℝ) - (M₀ : ℝ) ≤ M →
        (∀ m ∈ Finset.Icc M₀ M₁, |(m : ℝ)| ≤ C * M) →
        let I : Finset ℤ := Finset.Icc M₀ M₁
        let T₁ : ℝ := x ^ (ε / 2) * Qcenter / N₁
        let T₂ : ℝ := x ^ (ε / 2) * Qcenter / N₂
        let T₃ : ℝ := x ^ (ε / 2) * Qcenter / N₃
        let S : Finset (ℤ × ℤ × ℤ) :=
          ((Finset.Icc (Int.ceil (-T₁)) (Int.floor T₁)) ×ˢ
            ((Finset.Icc (Int.ceil (-T₂)) (Int.floor T₂)) ×ˢ
              (Finset.Icc (Int.ceil (-T₃)) (Int.floor T₃)))).filter
                (fun h => h.1 * h.2.1 * h.2.2 ≠ 0)
      ∀ (η : ℕ → ℂ) (α : ℤ → ℂ) (c : ℤ × ℤ × ℤ → ℂ)
        (Wη Wα Wc : ℝ), 0 ≤ Wη → 0 ≤ Wα → 0 ≤ Wc →
        (∀ q ∈ Qset, ‖η (q : ℕ)‖ ≤ Wη) →
        (∀ m ∈ I, ‖α m‖ ≤ Wα) →
        (∀ h ∈ S, ‖c h‖ ≤ Wc) →
      ∀ (Tψ Lw : ℝ) (ψ : ℝ → ℝ), 1 ≤ Tψ → 0 ≤ Lw →
        ContDiff ℝ ∞ ψ →
        (∀ t : ℝ, 0 ≤ ψ t) →
        (∀ t ∈ Set.Icc (-1 : ℝ) 1, ψ t = 1) →
        Function.support ψ ⊆ Set.Icc (-Tψ) Tψ →
        (∀ t : ℝ,
          ‖ψ t‖ ≤ Lw ∧ ‖deriv ψ t‖ ≤ Lw ∧ ‖deriv (deriv ψ) t‖ ≤ Lw) →
        let V : ℂ := ((N / Qcenter ^ 3 : ℝ) : ℂ) *
          ∑ q ∈ Qset, (q : ℂ) * η (q : ℕ) *
            ∑ m ∈ I, if hm : IsUnit (m : ZMod (q : ℕ)) then
              α m * ∑ h ∈ S, c h *
                typeIIICompleteFiberSum (q : ℕ)
                  (h.1 : ZMod (q : ℕ)) (h.2.1 : ZMod (q : ℕ))
                  (h.2.2 : ZMod (q : ℕ)) (a q * hm.unit⁻¹)
            else 0
        ‖V‖ ≤ K * Wc * Wη * Wα * Real.sqrt ((2 * Tψ + 3) * Lw) *
          (M * N) * x ^ (-3 * ε) := by
  have hweight_algebra (r b wc we wa s t z root : ℝ) :
      (r / b ^ 2) * (4 * wc * ((8 * C) * (2 * we) * wa * s * t / (b * root) * z)) =
        ((64 * C) * wc * we * wa * s * t * z) * (r / (root * b ^ 3)) := by
    simp only [div_eq_mul_inv, mul_inv_rev, ← inv_pow]
    ring
  have hfrequency_bound (T₁ T₂ T₃ : ℝ) (b₁ b₂ b₃ : ℕ)
      (hb₁ : 0 < b₁) (hb₂ : 0 < b₂) (hb₃ : 0 < b₃) (ℓ : ℤ × ℤ × ℤ)
      (h₁ : (b₁ : ℤ) * ℓ.1 ∈ Finset.Icc (Int.ceil (-T₁)) (Int.floor T₁))
      (h₂ : (b₂ : ℤ) * ℓ.2.1 ∈ Finset.Icc (Int.ceil (-T₂)) (Int.floor T₂))
      (h₃ : (b₃ : ℤ) * ℓ.2.2 ∈ Finset.Icc (Int.ceil (-T₃)) (Int.floor T₃)) :
      |((ℓ.1 * ℓ.2.1 * ℓ.2.2 : ℤ) : ℝ)| ≤
        T₁ * T₂ * T₃ / ((b₁ * b₂ * b₃ : ℕ) : ℝ) := by
    have hcoordinate (T : ℝ) (b : ℕ) (hb : 0 < b) (z : ℤ)
        (hz : (b : ℤ) * z ∈ Finset.Icc (Int.ceil (-T)) (Int.floor T)) :
        |(z : ℝ)| ≤ T / (b : ℝ) := by
      obtain ⟨hlo, hhi⟩ := Finset.mem_Icc.mp hz
      have habs : |(((b : ℤ) * z : ℤ) : ℝ)| ≤ T :=
        abs_le.mpr ⟨Int.ceil_le.mp hlo, Int.le_floor.mp hhi⟩
      rw [Int.cast_mul, Int.cast_natCast, abs_mul,
        abs_of_nonneg (Nat.cast_nonneg b)] at habs
      apply (le_div_iff₀ (by exact_mod_cast hb : 0 < (b : ℝ))).2
      simpa only [mul_comm] using habs
    have hu := hcoordinate T₁ b₁ hb₁ ℓ.1 h₁
    have hv := hcoordinate T₂ b₂ hb₂ ℓ.2.1 h₂
    have hw := hcoordinate T₃ b₃ hb₃ ℓ.2.2 h₃
    have hTu : 0 ≤ T₁ / (b₁ : ℝ) := (abs_nonneg _).trans hu
    have hTv : 0 ≤ T₂ / (b₂ : ℝ) := (abs_nonneg _).trans hv
    calc
      |((ℓ.1 * ℓ.2.1 * ℓ.2.2 : ℤ) : ℝ)| =
          |(ℓ.1 : ℝ)| * |(ℓ.2.1 : ℝ)| * |(ℓ.2.2 : ℝ)| := by
        simp only [Int.cast_mul, abs_mul]
      _ ≤ (T₁ / (b₁ : ℝ)) * (T₂ / (b₂ : ℝ)) * (T₃ / (b₃ : ℝ)) :=
        mul_le_mul (mul_le_mul hu hv (abs_nonneg _) hTu) hw
          (abs_nonneg _) (mul_nonneg hTu hTv)
      _ = T₁ * T₂ * T₃ / ((b₁ * b₂ * b₃ : ℕ) : ℝ) := by
        simp only [Nat.cast_mul, div_mul_div_comm]
  have hproject (b d : ℕ) (a : (ZMod (b * d))ˣ) (m : ℤ)
      (hm : IsUnit (m : ZMod (b * d))) :
      ((Units.map ((ZMod.castHom (Nat.dvd_mul_left d b) (ZMod d)).toMonoidHom)
          (a * hm.unit⁻¹) : (ZMod d)ˣ) : ZMod d) =
        ((Units.map ((ZMod.castHom (Nat.dvd_mul_left d b) (ZMod d)).toMonoidHom)
          a : (ZMod d)ˣ) : ZMod d) * (m : ZMod d)⁻¹ := by
    rw [map_mul, map_inv, Units.val_mul, ← ZMod.inv_coe_unit]
    congr 2
    change (ZMod.castHom (Nat.dvd_mul_left d b) (ZMod d))
      (hm.unit : ZMod (b * d)) = (m : ZMod d)
    rw [hm.unit_spec, map_intCast]
  have hunit_iff (q : ℕ) (m : ℤ) :
      Int.gcd m (q : ℤ) = 1 ↔ IsUnit (m : ZMod q) := by
    rw [ZMod.coe_int_isUnit_iff_isCoprime, Int.isCoprime_iff_gcd_eq_one, Int.gcd_comm]
  intro μ θ εcap
  let s : ℝ := typeIIIExtraction μ θ δ
  have hσpos : 0 < σ := by linarith only [hσ, hω, hδ]
  have hμ : 0 < μ := by dsimp only [μ, typeIIIMu]; linarith only [hσupper]
  have hμupper : μ < 1 / 4 := by dsimp only [μ, typeIIIMu]; linarith only [hσpos]
  have hA : 0 < typeIIIMarginA μ θ δ := (typeIII_criteria_equivalence σ omegaExp δ).1.mpr hσ
  have hB : 0 < typeIIIMarginB θ δ := (typeIII_criteria_equivalence σ omegaExp δ).2.mpr hswitch
  have hs : 0 < s := (typeIII_extraction_bounds hμ.le hδ hA hB).2.2.1
  refine ⟨typeIIIEpsilonCap_pos hA, ?_⟩
  intro ε hε hεcap
  have hnormalize (x M N Q : ℝ) (hx : 1 ≤ x) (hM0 : 0 < M) (hN0 : 0 < N)
      (hQ : 0 < Q) (hMNlo : x / C ≤ M * N) (hMNhi : M * N ≤ C * x)
      (hNlow : x ^ (3 / 4 + 3 * σ / 2 - ε) / C ≤ N)
      (hQup : Q ≤ C * x ^ (1 / 2 + 2 * omegaExp + ε)) :
      (N / Q ^ 2) * x ^ (5 * ε / 2) *
          linearFiveScale M Q (cappedExtractionScale x s (x ^ δ) Q) (x ^ δ) (Q ^ 3 / N) ≤
        10 * C ^ 8 * (M * N) * x ^ (-3 * ε) := by
    have hNlow' : x ^ (1 - μ - ε) / C ≤ N := by
      rw [show 1 - μ - ε = 3 / 4 + 3 * σ / 2 - ε by dsimp only [μ, typeIIIMu]; ring]
      exact hNlow
    exact normalized_cappedFiveScale_le hμ.le hμupper hδ hA hB hε hεcap
      hC hx hM0 hN0 hQ hMNlo hMNhi hNlow' hQup
  obtain ⟨Cbad, hCbad, hbadtotal⟩ :=
    exists_typeIII_bad_weight_sum_bound
  obtain ⟨Xc, _, hComp⟩ := hlocal.exists_fineBand_weighted_kl3_estimate hC₀
    (1 / 2 + 2 * omegaExp + ε) δ ε C s ε hδ hε hC hs hε
  let X : ℝ := max Xc (max 1 ((3 * C) ^ (1 / ε)))
  have hX : 1 ≤ X := (le_max_left _ _).trans (le_max_right _ _)
  refine ⟨640 * Cbad * C ^ 9, X, by positivity, hX, ?_⟩
  intro x hx
  have hx1 : 1 ≤ x := hX.trans hx
  have hx0 : 0 < x := zero_lt_one.trans_le hx1
  have hxC : Xc ≤ x := (le_max_left _ _).trans hx
  have hxpow : (3 * C) ^ (1 / ε) ≤ x :=
    (le_max_right _ _).trans ((le_max_right _ _).trans hx)
  have hCpow : 3 * C ≤ x ^ ε :=
    (Real.rpow_inv_le_iff_of_pos (by positivity) hx0.le hε).mp
      (by simpa only [one_div] using hxpow)
  have hband : C * x ^ (-ε) ≤ 1 / 3 := by
    rw [Real.rpow_neg hx0.le, ← div_eq_mul_inv]
    apply (div_le_iff₀ (Real.rpow_pos_of_pos hx0 ε)).2
    linarith only [hCpow]
  intro M N₁ N₂ N₃ Qcenter hM hN₁ hN₂ hN₃ hQ N hMNlo hMNhi hNlow hQup
  have hN : 1 ≤ N := one_le_mul_of_one_le_of_one_le
    (one_le_mul_of_one_le_of_one_le hN₁ hN₂) hN₃
  have hM0 : 0 < M := zero_lt_one.trans_le hM
  have hN0 : 0 < N := zero_lt_one.trans_le hN
  intro Y hY Qset hQset a₀ a ha M₀ M₁ hM₀ _hwidth hheight I T₁ T₂ T₃ S
    η α c Wη Wα Wc hWη hWα hWc hη hα hc Tψ Lw ψ hTψ hLw hψ hψnonneg hψone
    hψsupport hψbounds V
  let η' : ℕ → ℂ := fun n => (((n : ℝ) / Qcenter : ℝ) : ℂ) * η n
  have hη' (q : ℕ+) (hq : q ∈ Qset) : ‖η' (q : ℕ)‖ ≤ 2 * Wη := by
    have hqratio : (q : ℝ) / Qcenter ≤ 2 := by
      apply (div_le_iff₀ hQ).2
      have hqu := (hQset q hq).2.2.2
      have hbandQ := mul_le_mul_of_nonneg_left hband hQ.le
      nlinarith only [hqu, hbandQ, hQ]
    have hratio0 : 0 ≤ (q : ℝ) / Qcenter := by positivity
    calc
      ‖η' (q : ℕ)‖ = ((q : ℝ) / Qcenter) * ‖η (q : ℕ)‖ := by
        simp only [η', norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hratio0]
      _ ≤ 2 * Wη := mul_le_mul hqratio (hη q hq) (norm_nonneg _) (by norm_num)
  let P : ℤ × ℤ × ℤ → ℤ := fun h => h.1 * h.2.1 * h.2.2
  have hS (h : ℤ × ℤ × ℤ) (hh : h ∈ S) : P h ≠ 0 :=
    (Finset.mem_filter.mp hh).2
  let part : ℕ+ → ℤ → ℕ := fun q z =>
    ∏ p ∈ (q : ℕ).primeFactors, p ^ z.natAbs.factorization p
  let parts : ℕ+ → ℤ × ℤ × ℤ → ℕ × ℕ × ℕ := fun q h =>
    (part q h.1, part q h.2.1, part q h.2.2)
  have hpart (q : ℕ+) (hq : q ∈ Qset) (z : ℤ) (hz : z ≠ 0) :
      0 < part q z ∧ part q z ∈ Nat.factoredNumbers (q : ℕ).primeFactors := by
    obtain ⟨hp, _, _, _, _, hs, _, _, _⟩ :=
      typeIII_signed_supported_prime_part (q : ℕ) (hQset q hq).1 z hz
    exact ⟨hp, hs⟩
  let R : Finset (ℕ × ℕ × ℕ) := (Qset ×ˢ S).image (fun z => parts z.1 z.2)
  let F : (ℕ × ℕ × ℕ) → ℕ+ → Finset (ℤ × ℤ × ℤ) := fun v q =>
    S.filter (fun h => P h ≠ 0 ∧ part q h.1 = v.1 ∧
      part q h.2.1 = v.2.1 ∧ part q h.2.2 = v.2.2)
  have hF (q : ℕ+) (v : ℕ × ℕ × ℕ) :
      S.filter (fun h => parts q h = v) = F v q := by
    apply Finset.filter_congr
    intro h hh
    simp only [parts, Prod.ext_iff]
    exact ⟨fun heq => ⟨hS h hh, heq⟩, And.right⟩
  have hsplit (q : ℕ+) (hq : q ∈ Qset) (f : ℤ × ℤ × ℤ → ℂ) :
      (∑ h ∈ S, f h) = ∑ v ∈ R, ∑ h ∈ F v q, f h := by
    have hm : ∀ h ∈ S, parts q h ∈ R := fun h hh =>
      Finset.mem_image.mpr ⟨(q, h), Finset.mem_product.mpr ⟨hq, hh⟩, rfl⟩
    simpa only [hF] using
      (Finset.sum_fiberwise_of_maps_to (s := S) (t := R) (g := parts q) hm f).symm
  have hRpos (v : ℕ × ℕ × ℕ) (hv : v ∈ R) :
      0 < v.1 ∧ 0 < v.2.1 ∧ 0 < v.2.2 := by
    obtain ⟨⟨q, h⟩, hqh, rfl⟩ := Finset.mem_image.mp hv
    obtain ⟨hq, hh⟩ := Finset.mem_product.mp hqh
    have hz : h.1 ≠ 0 ∧ h.2.1 ≠ 0 ∧ h.2.2 ≠ 0 := by
      simpa only [P, mul_ne_zero_iff, and_assoc] using hS h hh
    exact ⟨(hpart q hq h.1 hz.1).1, (hpart q hq h.2.1 hz.2.1).1,
      (hpart q hq h.2.2 hz.2.2).1⟩
  have hrad_dvd (v : ℕ × ℕ × ℕ) (q : ℕ+) (hq : q ∈ Qset)
      (h : ℤ × ℤ × ℤ) (hh : h ∈ F v q) :
      (radical (v.1 * v.2.1 * v.2.2) : ℕ) ∣ (q : ℕ) := by
    obtain ⟨_, hz, h₁, h₂, h₃⟩ := Finset.mem_filter.mp hh
    have hz' : h.1 ≠ 0 ∧ h.2.1 ≠ 0 ∧ h.2.2 ≠ 0 := by
      simpa only [P, mul_ne_zero_iff, and_assoc] using hz
    apply (Nat.radical_dvd_iff (PNat.ne_zero q)).2
    apply Nat.primeFactors_subset_of_mem_factoredNumbers
    rw [← h₁, ← h₂, ← h₃]
    exact Nat.mul_mem_factoredNumbers
      (Nat.mul_mem_factoredNumbers (hpart q hq h.1 hz'.1).2
        (hpart q hq h.2.1 hz'.2.1).2) (hpart q hq h.2.2 hz'.2.2).2
  let G : (ℕ × ℕ × ℕ) → ℂ := fun v =>
    ∑ q ∈ Qset, η' (q : ℕ) *
      ∑ m ∈ I, if hm : IsUnit (m : ZMod (q : ℕ)) then
        α m * ∑ h ∈ F v q, c h * typeIIICompleteFiberSum (q : ℕ)
          (h.1 : ZMod (q : ℕ)) (h.2.1 : ZMod (q : ℕ)) (h.2.2 : ZMod (q : ℕ))
          (a q * hm.unit⁻¹)
      else 0
  have hpartition :
      (∑ q ∈ Qset, η' (q : ℕ) *
        ∑ m ∈ I, if hm : IsUnit (m : ZMod (q : ℕ)) then
          α m * ∑ h ∈ S, c h * typeIIICompleteFiberSum (q : ℕ)
            (h.1 : ZMod (q : ℕ)) (h.2.1 : ZMod (q : ℕ)) (h.2.2 : ZMod (q : ℕ))
            (a q * hm.unit⁻¹)
        else 0) = ∑ v ∈ R, G v := by
    symm
    dsimp only [G]
    rw [Finset.sum_comm]
    apply Finset.sum_congr rfl
    intro q hq
    rw [← Finset.mul_sum]
    congr 1
    rw [Finset.sum_comm]
    apply Finset.sum_congr rfl
    intro m hm
    by_cases hu : IsUnit (m : ZMod (q : ℕ))
    · simp only [dite_eq_left hu]
      rw [hsplit q hq, Finset.mul_sum]
    · simp only [dite_eq_right hu, Finset.sum_const_zero]
  have hV : V = (((N / Qcenter ^ 2 : ℝ) : ℂ)) * ∑ v ∈ R, G v := by
    rw [← hpartition]
    dsimp only [V, η']
    rw [Finset.mul_sum, Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro q hq
    have hQz : (Qcenter : ℂ) ≠ 0 := by exact_mod_cast hQ.ne'
    push_cast
    field_simp [hQz]
  let H : ℝ := Qcenter ^ 3 / N
  let Zsum : ℝ := linearFiveScale M Qcenter
    (cappedExtractionScale x s (Y : ℝ) Qcenter) (Y : ℝ) H
  let E : ℝ := (64 * C) * Wc * Wη * Wα * Real.sqrt ((2 * Tψ + 3) * Lw) *
    x ^ (5 * ε / 2) * Zsum
  let weight : ℕ × ℕ × ℕ → ℝ := fun v =>
    (((radical v.1 : ℕ) : ℝ) * ((radical v.2.1 : ℕ) : ℝ) * ((radical v.2.2 : ℕ) : ℝ)) /
      (Real.sqrt ((v.1 * v.2.1 * v.2.2 : ℕ) : ℝ) *
        ((radical (v.1 * v.2.1 * v.2.2) : ℕ) : ℝ) ^ 3)
  have hE : 0 ≤ E := by 
    have hCpos : 0 < C := zero_lt_one.trans_le hC
    have hYpos : 0 < (Y : ℝ) := zero_lt_one.trans_le Y.property
    have hcap : 0 ≤ cappedExtractionScale x s (Y : ℝ) Qcenter := by
      exact le_min (Real.rpow_nonneg hx0.le _) (by positivity)
    have hZ : 0 ≤ Zsum := linearFiveScale_nonneg hM0.le hQ.le hcap hYpos.le
      (by dsimp only [H]; positivity)
    dsimp only [E]
    positivity
  have hGbound (v : ℕ × ℕ × ℕ) (hv : v ∈ R) : ‖G v‖ ≤ E * weight v := by
    obtain ⟨hv₁, hv₂, hv₃⟩ := hRpos v hv
    let B : ℕ := v.1 * v.2.1 * v.2.2
    let b : ℕ+ := ⟨radical B, Nat.radical_pos B⟩
    let D : Finset ℕ+ := Qset.preimage (fun d : ℕ+ => b * d)
      (fun _ _ _ _ h => mul_left_cancel h)
    have hDmem (d : ℕ+) : d ∈ D ↔ b * d ∈ Qset := Finset.mem_preimage
    have hD (d : ℕ+) (hd : d ∈ D) :
        Squarefree ((b : ℕ) * (d : ℕ)) ∧
        Nonempty (DenseDivisibilityWitness Y 1 ((b : ℕ) * (d : ℕ))) ∧
        Qcenter * (1 - C * x ^ (-ε)) ≤ (b : ℝ) * (d : ℝ) ∧
        (b : ℝ) * (d : ℝ) ≤ Qcenter * (1 + C * x ^ (-ε)) := by
      simpa only [PNat.mul_coe, Nat.cast_mul] using hQset (b * d) ((hDmem d).mp hd)
    have hFempty (q : ℕ+) (hq : q ∈ Qset) (hbq : ¬ b ∣ q) : F v q = ∅ := by
      apply Finset.eq_empty_iff_forall_notMem.mpr
      intro h hh
      exact hbq (PNat.dvd_iff.mpr (hrad_dvd v q hq h hh))
    let ad : ∀ d : ℕ+, (ZMod ((b : ℕ) * (d : ℕ)))ˣ := fun d => a (b * d)
    let A_d : ∀ d : ℕ+, (ZMod (d : ℕ))ˣ := fun d =>
      Units.map ((ZMod.castHom (Nat.dvd_mul_left (d : ℕ) (b : ℕ))
        (ZMod (d : ℕ))).toMonoidHom) (ad d)
    let rebuild : ℤ × ℤ × ℤ → ℤ × ℤ × ℤ := fun ℓ =>
      ((v.1 : ℤ) * ℓ.1, (v.2.1 : ℤ) * ℓ.2.1, (v.2.2 : ℤ) * ℓ.2.2)
    have hreb_inj : Function.Injective rebuild :=
      (mul_right_injective₀ (by exact_mod_cast hv₁.ne')).prodMap
        ((mul_right_injective₀ (by exact_mod_cast hv₂.ne')).prodMap
          (mul_right_injective₀ (by exact_mod_cast hv₃.ne')))
    let U : Finset (ℤ × ℤ × ℤ) :=
      (S.preimage rebuild (fun _ _ _ _ h => hreb_inj h)).filter
        (fun ℓ => Int.gcd (P ℓ) ((b : ℕ) : ℤ) = 1)
    have hUmem (ℓ : ℤ × ℤ × ℤ) : ℓ ∈ U ↔
        rebuild ℓ ∈ S ∧ Int.gcd (P ℓ) ((b : ℕ) : ℤ) = 1 :=
      Finset.mem_filter.trans (and_congr Finset.mem_preimage Iff.rfl)
    have hreb_nonzero (ℓ : ℤ × ℤ × ℤ) (hℓ : rebuild ℓ ∈ S) : P ℓ ≠ 0 := by
      simpa [P, rebuild, mul_ne_zero_iff, hv₁.ne', hv₂.ne', hv₃.ne', and_assoc]
        using hS (rebuild ℓ) hℓ
    have hUprod (ℓ : ℤ × ℤ × ℤ) (hℓ : ℓ ∈ U) : P ℓ ≠ 0 :=
      hreb_nonzero ℓ ((hUmem ℓ).mp hℓ).1
    let Ld : ℕ+ → Finset (ℤ × ℤ × ℤ) := fun d => (F v (b * d)).image (fun h =>
      (h.1 / (v.1 : ℤ), h.2.1 / (v.2.1 : ℤ), h.2.2 / (v.2.2 : ℤ)))
    have hLd (d : ℕ+) (hd : d ∈ D) : Ld d =
        U.filter (fun ℓ => Int.gcd (((b : ℕ) : ℤ) * P ℓ) ((d : ℕ) : ℤ) = 1) := by
      obtain ⟨hL, _, _, _⟩ := typeIII_full_supported_frequency_fiber_kl3
        (b : ℕ) (d : ℕ) v.1 v.2.1 v.2.2 (hD d hd).1 hv₁ hv₂ hv₃ rfl S c 1
      have hbd : IsCoprime ((b : ℕ) : ℤ) ((d : ℕ) : ℤ) :=
        (Nat.coprime_of_squarefree_mul (hD d hd).1).isCoprime
      ext ℓ
      have hm : ℓ ∈ Ld d ↔ rebuild ℓ ∈ S ∧ P ℓ ≠ 0 ∧
          Int.gcd (P ℓ) (((b : ℕ) * (d : ℕ) : ℕ) : ℤ) = 1 := hL ℓ
      rw [hm]
      conv_rhs => rw [Finset.mem_filter, hUmem, and_assoc]
      simp only [← Int.isCoprime_iff_gcd_eq_one, Nat.cast_mul,
        IsCoprime.mul_right_iff, IsCoprime.mul_left_iff, hbd, true_and]
      exact and_congr_right fun hs => by simp [hreb_nonzero ℓ hs]
    let bad : ℂ := typeIIICompleteFiberSum (b : ℕ)
      (v.1 : ZMod (b : ℕ)) (v.2.1 : ZMod (b : ℕ)) (v.2.2 : ZMod (b : ℕ)) 1
    let phase : ℕ+ → ℤ → ℤ → ℂ := fun d m z => normalizedKloosterman3Mod (d : ℕ)
      ((A_d d : ZMod (d : ℕ)) * (B : ZMod (d : ℕ)) * (z : ZMod (d : ℕ)) *
        (m : ZMod (d : ℕ))⁻¹ * (((b : ℕ) : ZMod (d : ℕ))⁻¹) ^ 3)
    have hFRsum (d : ℕ+) (hd : d ∈ D) (m : ℤ)
        (hm : IsUnit (m : ZMod ((b : ℕ) * (d : ℕ)))) :
        (∑ h ∈ F v (b * d), c h * typeIIICompleteFiberSum ((b : ℕ) * (d : ℕ))
          (h.1 : ZMod ((b : ℕ) * (d : ℕ))) (h.2.1 : ZMod ((b : ℕ) * (d : ℕ)))
          (h.2.2 : ZMod ((b : ℕ) * (d : ℕ))) (ad d * hm.unit⁻¹)) =
        bad * ∑ ℓ ∈ U, if Int.gcd (((b : ℕ) : ℤ) * P ℓ) ((d : ℕ) : ℤ) = 1 then
          c (rebuild ℓ) * phase d m (P ℓ) else 0 := by
      have hf := (typeIII_full_supported_frequency_fiber_kl3 (b : ℕ) (d : ℕ)
        v.1 v.2.1 v.2.2 (hD d hd).1 hv₁ hv₂ hv₃ rfl S c (ad d * hm.unit⁻¹)).2.1
      change (∑ h ∈ F v (b * d), _) = bad * ∑ ℓ ∈ Ld d, _ at hf
      rw [hf, hLd d hd, Finset.sum_filter]
      congr 1
      apply Finset.sum_congr rfl
      intro ℓ hℓ
      dsimp only [phase]
      congr 3
      rw [hproject]
      dsimp only [A_d]
      ring
    let dterm : ℕ+ → ℤ → ℂ := fun d z =>
      if Int.gcd (((b : ℕ) : ℤ) * z) ((d : ℕ) : ℤ) = 1 then
        η' ((b : ℕ) * (d : ℕ)) * ∑ m ∈ I,
          if Int.gcd m (((b : ℕ) * (d : ℕ) : ℕ) : ℤ) = 1 then
            α m * phase d m z else 0
      else 0
    let K : ℤ → ℂ := fun z => ∑ d ∈ D, dterm d z
    have hbyd (d : ℕ+) (hd : d ∈ D) :
        η' ((b : ℕ) * (d : ℕ)) *
          (∑ m ∈ I, if hm : IsUnit (m : ZMod ((b : ℕ) * (d : ℕ))) then
            α m * ∑ h ∈ F v (b * d), c h * typeIIICompleteFiberSum ((b : ℕ) * (d : ℕ))
              (h.1 : ZMod ((b : ℕ) * (d : ℕ))) (h.2.1 : ZMod ((b : ℕ) * (d : ℕ)))
              (h.2.2 : ZMod ((b : ℕ) * (d : ℕ))) (ad d * hm.unit⁻¹)
          else 0) = bad * ∑ ℓ ∈ U, c (rebuild ℓ) * dterm d (P ℓ) := by
      calc
        _ = ∑ m ∈ I, ∑ ℓ ∈ U, bad * c (rebuild ℓ) *
            (if Int.gcd (((b : ℕ) : ℤ) * P ℓ) ((d : ℕ) : ℤ) = 1 then
              η' ((b : ℕ) * (d : ℕ)) *
                (if Int.gcd m (((b : ℕ) * (d : ℕ) : ℕ) : ℤ) = 1 then
                  α m * phase d m (P ℓ) else 0)
            else 0) := by
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro m hmI
          by_cases hm : IsUnit (m : ZMod ((b : ℕ) * (d : ℕ)))
          · have hmg := (hunit_iff ((b : ℕ) * (d : ℕ)) m).mpr hm
            simp only [dite_eq_left hm, ite_eq_left hmg]
            rw [hFRsum d hd m hm]
            simp only [Finset.mul_sum]
            apply Finset.sum_congr rfl
            intro ℓ hℓ
            split_ifs <;> ring
          · have hmg : Int.gcd m (((b : ℕ) * (d : ℕ) : ℕ) : ℤ) ≠ 1 :=
              fun hg => hm ((hunit_iff ((b : ℕ) * (d : ℕ)) m).mp hg)
            simp only [dite_eq_right hm, ite_eq_right hmg, mul_zero, ite_self,
              Finset.sum_const_zero]
        _ = _ := by
          rw [Finset.sum_comm]
          simp only [dterm, Finset.mul_sum, mul_ite, mul_zero,
            Finset.sum_ite_irrel, Finset.sum_const_zero, mul_assoc]
    have hGexact : G v = bad * ∑ ℓ ∈ U, c (rebuild ℓ) * K (P ℓ) := by
      dsimp only [G]
      rw [← Finset.sum_preimage (fun d : ℕ+ => b * d) Qset
        (fun _ _ _ _ h => mul_left_cancel h) _
        (fun q hq hnot => by
          simp [hFempty q hq (fun hbq => hnot (Exists.imp (fun _ hd => hd.symm) hbq))])]
      trans ∑ d ∈ D, bad * ∑ ℓ ∈ U, c (rebuild ℓ) * dterm d (P ℓ)
      · exact Finset.sum_congr rfl hbyd
      rw [← Finset.mul_sum, Finset.sum_comm]
      simp only [K, Finset.mul_sum]
    let Hb : ℝ := x ^ (3 * ε / 2) * H / (B : ℝ)
    let L : Finset ℤ := (Finset.Icc (Int.ceil (-Hb)) (Int.floor Hb)).filter (fun z => z ≠ 0)
    let τ₃ : ℤ → ℝ := fun z => (((ArithmeticFunction.zeta : ArithmeticFunction ℕ) ^ 3) z.natAbs : ℝ)
    let J : ℝ := ∑ z ∈ L, τ₃ z * ‖K z‖
    have hUL : U.image P ⊆ L := by
      intro z hz
      obtain ⟨ℓ, hℓ, rfl⟩ := Finset.mem_image.mp hz
      have hs := (hUmem ℓ).mp hℓ
      obtain ⟨hbox, _⟩ := Finset.mem_filter.mp hs.1
      obtain ⟨h₁, h₂₃⟩ := Finset.mem_product.mp hbox
      obtain ⟨h₂, h₃⟩ := Finset.mem_product.mp h₂₃
      have habs := hfrequency_bound T₁ T₂ T₃ v.1 v.2.1 v.2.2 hv₁ hv₂ hv₃ ℓ h₁ h₂ h₃
      have hvolume : T₁ * T₂ * T₃ / (B : ℝ) = Hb := by
        dsimp only [T₁, T₂, T₃, Hb, H, N]
        rw [show 3 * ε / 2 = ε / 2 * (3 : ℝ) by ring, Real.rpow_mul hx0.le,
          Real.rpow_ofNat]
        simp only [div_mul_div_comm]
        ring
      have hbound : |((P ℓ : ℤ) : ℝ)| ≤ Hb := habs.trans_eq hvolume
      exact Finset.mem_filter.mpr ⟨Finset.mem_Icc.mpr
        ⟨Int.ceil_le.mpr (abs_le.mp hbound).1, Int.le_floor.mpr (abs_le.mp hbound).2⟩,
        hUprod ℓ hℓ⟩
    have hτ (z : ℤ) : 0 ≤ τ₃ z := Nat.cast_nonneg _
    have hJsub : (∑ z ∈ U.image P, τ₃ z * ‖K z‖) ≤ J :=
      Finset.sum_le_sum_of_subset_of_nonneg hUL (fun z _ _ => mul_nonneg (hτ z) (norm_nonneg _))
    let W : ℝ := ((U.sup (fun ℓ => ‖c (rebuild ℓ)‖₊) : ℝ≥0) : ℝ)
    have hW : W ≤ Wc :=
      NNReal.coe_le_coe.mpr
        (show U.sup (fun ℓ => ‖c (rebuild ℓ)‖₊) ≤ (⟨Wc, hWc⟩ : ℝ≥0) from
          Finset.sup_le fun ℓ hℓ =>
            NNReal.coe_le_coe.mp (hc (rebuild ℓ) ((hUmem ℓ).mp hℓ).1))
    have hreg : ‖∑ ℓ ∈ U, c (rebuild ℓ) * K (P ℓ)‖ ≤ 4 * Wc * J := by
      have ht := (typeIII_signed_product_regrouped_kl3_bound b v.1 v.2.1 v.2.2 D I η' α ad
        U (fun ℓ => c (rebuild ℓ)) hUprod).2.2
      exact ht.trans (mul_le_mul (mul_le_mul_of_nonneg_left hW (by norm_num)) hJsub
        (Finset.sum_nonneg (fun z _ => mul_nonneg (hτ z) (norm_nonneg _))) (by positivity))
    have hJ : J ≤ (8 * C) * (2 * Wη) * Wα * Real.sqrt ((2 * Tψ + 3) * Lw) *
        x ^ (5 * ε / 2) / ((b : ℝ) * Real.sqrt (B : ℝ)) * Zsum :=
      by
        have hh := hComp x hxC M N Qcenter hM hN hQ hMNhi hQup Y hY
          b v.1 v.2.1 v.2.2 hv₁ hv₂ hv₃ rfl D hD a₀ ad
          (fun d hd => ha (b * d) ((hDmem d).mp hd)) M₀ M₁ hM₀ hheight
          η' α (2 * Wη) Wα Tψ Lw (by positivity) hWα hTψ hLw
          (fun d hd => hη' (b * d) ((hDmem d).mp hd)) hα
          ψ hψ hψnonneg hψone hψsupport hψbounds
        simpa only [selectedKloostermanL1, weightedKernelL1, selectedFrequencyRange,
          ternaryDivisorWeight, selectedKloostermanTerm, J, L, τ₃, K, dterm, phase,
          A_d, I, H, Hb, B, Zsum,
          show ε + 3 * ε / 2 = 5 * ε / 2 by ring] using hh
    have hbad : ‖bad‖ ≤
        (((radical v.1 : ℕ) : ℝ) * ((radical v.2.1 : ℕ) : ℝ) * ((radical v.2.2 : ℕ) : ℝ)) /
          (b : ℝ) ^ 2 :=
      (typeIII_full_supported_frequency_fiber_kl3 (b : ℕ) 1 v.1 v.2.1 v.2.2
        (by simpa only [mul_one, b, PNat.mk_coe] using
          (UniqueFactorizationMonoid.squarefree_radical (a := B))) hv₁ hv₂ hv₃ rfl S c 1).2.2.2
    calc
      ‖G v‖ = ‖bad‖ * ‖∑ ℓ ∈ U, c (rebuild ℓ) * K (P ℓ)‖ := by rw [hGexact, norm_mul]
      _ ≤ ((((radical v.1 : ℕ) : ℝ) * ((radical v.2.1 : ℕ) : ℝ) *
          ((radical v.2.2 : ℕ) : ℝ)) / (b : ℝ) ^ 2) * (4 * Wc * J) :=
        mul_le_mul hbad hreg (norm_nonneg _) (by positivity)
      _ ≤ ((((radical v.1 : ℕ) : ℝ) * ((radical v.2.1 : ℕ) : ℝ) *
          ((radical v.2.2 : ℕ) : ℝ)) / (b : ℝ) ^ 2) *
          (4 * Wc * ((8 * C) * (2 * Wη) * Wα * Real.sqrt ((2 * Tψ + 3) * Lw) *
            x ^ (5 * ε / 2) / ((b : ℝ) * Real.sqrt (B : ℝ)) * Zsum)) :=
        mul_le_mul_of_nonneg_left (mul_le_mul_of_nonneg_left hJ (by positivity)) (by positivity)
      _ = E * weight v :=
        hweight_algebra
          ((((radical v.1 : ℕ) : ℝ) * ((radical v.2.1 : ℕ) : ℝ)) *
            ((radical v.2.2 : ℕ) : ℝ))
          (b : ℝ) Wc Wη Wα (Real.sqrt ((2 * Tψ + 3) * Lw))
          (x ^ (5 * ε / 2)) Zsum (Real.sqrt (B : ℝ))
  have hweights : (∑ v ∈ R, weight v) ≤ Cbad := hbadtotal R hRpos
  have hraw : ‖∑ v ∈ R, G v‖ ≤ E * Cbad := by
    calc
      ‖∑ v ∈ R, G v‖ ≤ ∑ v ∈ R, E * weight v := norm_sum_le_of_le _ hGbound
      _ = E * ∑ v ∈ R, weight v := (Finset.mul_sum _ _ _).symm
      _ ≤ E * Cbad := mul_le_mul_of_nonneg_left hweights hE
  have hnormalized : (N / Qcenter ^ 2) * x ^ (5 * ε / 2) * Zsum ≤
      10 * C ^ 8 * (M * N) * x ^ (-3 * ε) :=
    by simpa only [Zsum, H, hY] using
      hnormalize x M N Qcenter hx1 hM0 hN0 hQ hMNlo hMNhi hNlow hQup
  have hEeq : E = (64 * C) * Wc * Wη * Wα * Real.sqrt ((2 * Tψ + 3) * Lw) *
      x ^ (5 * ε / 2) * Zsum := rfl
  clear_value V G R E Zsum H N weight η' part parts F S I T₁ T₂ T₃
  clear hComp hnormalize hGbound hweights hbadtotal hRpos hrad_dvd hpart hF hsplit hpartition
    hS hη'
  have hNQ : 0 ≤ N / Qcenter ^ 2 := by positivity
  calc
    ‖V‖ = (N / Qcenter ^ 2) * ‖∑ v ∈ R, G v‖ := by
      rw [hV, norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hNQ]
    _ ≤ (N / Qcenter ^ 2) * (E * Cbad) := mul_le_mul_of_nonneg_left hraw hNQ
    _ = ((64 * C) * Cbad * Wc * Wη * Wα * Real.sqrt ((2 * Tψ + 3) * Lw)) *
        ((N / Qcenter ^ 2) * x ^ (5 * ε / 2) * Zsum) := by rw [hEeq]; ring
    _ ≤ ((64 * C) * Cbad * Wc * Wη * Wα * Real.sqrt ((2 * Tψ + 3) * Lw)) *
        (10 * C ^ 8 * (M * N) * x ^ (-3 * ε)) :=
      mul_le_mul_of_nonneg_left
        hnormalized
        (mul_nonneg
          (mul_nonneg (mul_nonneg (mul_nonneg
            (mul_nonneg (by positivity : (0 : ℝ) ≤ (64 * C)) hCbad.le) hWc) hWη) hWα)
          (Real.sqrt_nonneg _))
    _ = (640 * Cbad * C ^ 9) * Wc * Wη * Wα *
        Real.sqrt ((2 * Tψ + 3) * Lw) * (M * N) * x ^ (-3 * ε) := by ring


#print axioms LocalFourierHypothesis.fineBand_nonzero_fourier_power_saving

end

end PrimeGap182.TypeIII
