import TypeIIITorsionCoefficientQuotient
import Mathlib.Algebra.Module.Torsion.Free

/-!
# Exact scalar kernels for the original coefficient reductions

Multiplication by every power of ell is injective in the actual coefficient
limit, because that ring is free over the ell-adic integers. The kernel
of each original finite reduction is the ideal generated by the stated
power of ell. At a finite level the annihilator of an ell power is given
by the complementary power, with no change of coefficient model.

These are ring and module statements used for the original sheaf
Bockstein maps. They assert no cohomological or adic comparison.
-/

noncomputable section

namespace PrimeGap182.TypeIII

/-- Freeness over the actual ell-adic integers makes every ell power
regular in the original coefficient-limit ring. -/
theorem torsionCoefficientLimit_mul_ell_pow_injective (p ell a : ℕ)
    [Fact p.Prime] [Fact ell.Prime] :
    Function.Injective (fun x : TorsionCoefficientLimit p ell =>
      (ell : TorsionCoefficientLimit p ell) ^ a * x) := by
  have hne : (ell : ℤ_[ell]) ^ a ≠ 0 :=
    pow_ne_zero a (Nat.cast_ne_zero.mpr (Fact.out : ell.Prime).ne_zero)
  simpa only [Algebra.smul_def, map_pow, map_natCast] using
    (smul_right_injective (TorsionCoefficientLimit p ell) hne)

/-- The same scalar is regular on both sides of the commutative limit ring. -/
theorem torsionCoefficientLimit_ell_pow_isRegular (p ell a : ℕ)
    [Fact p.Prime] [Fact ell.Prime] :
    IsRegular ((ell : TorsionCoefficientLimit p ell) ^ a) := by
  refine ⟨torsionCoefficientLimit_mul_ell_pow_injective p ell a, ?_⟩
  intro x y hxy
  apply torsionCoefficientLimit_mul_ell_pow_injective p ell a
  simpa only [mul_comm] using hxy

/-- The stated lower-level ell power vanishes under the original finite reduction. -/
theorem torsionCoefficientReduce_ell_pow (p ell : ℕ)
    [Fact p.Prime] [Fact ell.Prime] {m n : ℕ} (hmn : m ≤ n) :
    torsionCoefficientReduce p ell hmn
      ((ell : TorsionCoefficientRing p ell n) ^ (m + 1)) = 0 := by
  rw [map_pow, map_natCast, ← Nat.cast_pow]
  exact CharP.cast_eq_zero (TorsionCoefficientRing p ell m) (ell ^ (m + 1))

/-- The kernel of the original finite reduction is exactly divisibility
by the lower-level ell power in the original upper-level ring. -/
theorem torsionCoefficientReduce_eq_zero_iff (p ell : ℕ)
    [Fact p.Prime] [Fact ell.Prime] {m n : ℕ} (hmn : m ≤ n)
    (x : TorsionCoefficientRing p ell n) :
    torsionCoefficientReduce p ell hmn x = 0 ↔
      (ell : TorsionCoefficientRing p ell n) ^ (m + 1) ∣ x := by
  constructor
  · intro hx
    obtain ⟨y, rfl⟩ := torsionCoefficientLimitProjection_surjective p ell n x
    have hy : torsionCoefficientLimitProjection p ell m y = 0 := by
      rw [← RingHom.congr_fun (torsionCoefficientLimitProjection_compatible p ell hmn) y]
      exact hx
    obtain ⟨z, hz⟩ := (torsionCoefficientLimitProjection_eq_zero_iff p ell m y).mp hy
    refine ⟨torsionCoefficientLimitProjection p ell n z, ?_⟩
    simpa only [map_mul, map_pow, map_natCast] using
      congrArg (torsionCoefficientLimitProjection p ell n) hz
  · rintro ⟨y, rfl⟩
    rw [map_mul, torsionCoefficientReduce_ell_pow, zero_mul]

/-- The ideal kernel uses the unchanged finite reduction map. -/
theorem torsionCoefficientReduce_ker (p ell : ℕ)
    [Fact p.Prime] [Fact ell.Prime] {m n : ℕ} (hmn : m ≤ n) :
    RingHom.ker (torsionCoefficientReduce p ell hmn) =
      Ideal.span {(ell : TorsionCoefficientRing p ell n) ^ (m + 1)} := by
  ext x
  rw [RingHom.mem_ker, Ideal.mem_span_singleton, torsionCoefficientReduce_eq_zero_iff]

/-- At the original level n, the annihilator of ell^a is the image of
the complementary ell power. -/
theorem torsionCoefficientRing_ell_pow_mul_eq_zero_iff (p ell n a : ℕ)
    [Fact p.Prime] [Fact ell.Prime] (ha : a ≤ n + 1)
    (x : TorsionCoefficientRing p ell n) :
    (ell : TorsionCoefficientRing p ell n) ^ a * x = 0 ↔
      (ell : TorsionCoefficientRing p ell n) ^ (n + 1 - a) ∣ x := by
  have hexp : a + (n + 1 - a) = n + 1 := Nat.add_sub_of_le ha
  constructor
  · intro hx
    obtain ⟨y, rfl⟩ := torsionCoefficientLimitProjection_surjective p ell n x
    have hzero : torsionCoefficientLimitProjection p ell n
        ((ell : TorsionCoefficientLimit p ell) ^ a * y) = 0 := by
      simpa only [map_mul, map_pow, map_natCast] using hx
    obtain ⟨z, hz⟩ :=
      (torsionCoefficientLimitProjection_eq_zero_iff p ell n _).mp hzero
    have hy : y = (ell : TorsionCoefficientLimit p ell) ^ (n + 1 - a) * z := by
      apply torsionCoefficientLimit_mul_ell_pow_injective p ell a
      calc
        (ell : TorsionCoefficientLimit p ell) ^ a * y =
            (ell : TorsionCoefficientLimit p ell) ^ (n + 1) * z := hz
        _ = (ell : TorsionCoefficientLimit p ell) ^ a *
            ((ell : TorsionCoefficientLimit p ell) ^ (n + 1 - a) * z) := by
          rw [← mul_assoc, ← pow_add, hexp]
    refine ⟨torsionCoefficientLimitProjection p ell n z, ?_⟩
    simpa only [map_mul, map_pow, map_natCast] using
      congrArg (torsionCoefficientLimitProjection p ell n) hy
  · rintro ⟨y, rfl⟩
    rw [← mul_assoc, ← pow_add, hexp, ← Nat.cast_pow]
    rw [CharP.cast_eq_zero (TorsionCoefficientRing p ell n) (ell ^ (n + 1)), zero_mul]

/-- The original finite reduction kernel is also the kernel of the
complementary scalar multiplication on the same upper-level ring. -/
theorem torsionCoefficientReduce_eq_zero_iff_ell_pow_mul (p ell : ℕ)
    [Fact p.Prime] [Fact ell.Prime] {m n : ℕ} (hmn : m ≤ n)
    (x : TorsionCoefficientRing p ell n) :
    torsionCoefficientReduce p ell hmn x = 0 ↔
      (ell : TorsionCoefficientRing p ell n) ^ (n - m) * x = 0 := by
  rw [torsionCoefficientReduce_eq_zero_iff,
    torsionCoefficientRing_ell_pow_mul_eq_zero_iff p ell n (n - m)
      (le_trans (Nat.sub_le n m) (Nat.le_succ n))]
  have hexp : n + 1 - (n - m) = m + 1 := by omega
  rw [hexp]

#print axioms torsionCoefficientLimit_mul_ell_pow_injective
#print axioms torsionCoefficientLimit_ell_pow_isRegular
#print axioms torsionCoefficientReduce_ell_pow
#print axioms torsionCoefficientReduce_eq_zero_iff
#print axioms torsionCoefficientReduce_ker
#print axioms torsionCoefficientRing_ell_pow_mul_eq_zero_iff
#print axioms torsionCoefficientReduce_eq_zero_iff_ell_pow_mul

end PrimeGap182.TypeIII
