import Mathlib

/-!
# Elementary representation steps for tame ramification

The cyclic branch representation, its root-of-unity eigenvector, and scalar
twists below are actual linear maps. This file does not identify a geometric
inertia representation or the meaning of sheaf tameness.
-/

noncomputable section

namespace PrimeGap182.TypeIII

open scoped Classical

set_option maxHeartbeats 1000000

section BranchPermutation

variable (k G : Type*) [Field k] [Group G]

/-- The actual permutation representation on branch-indexed functions.
The underlying permutation is right multiplication on the group. -/
def branchPermutationRepresentation : G →* LinearMap.GeneralLinearGroup k (G → k) where
  toFun g := LinearMap.GeneralLinearGroup.ofLinearEquiv
    (LinearEquiv.funCongrLeft k k (Equiv.mulRight g))
  map_one' := by
    apply Units.ext
    ext f x
    simp [LinearMap.GeneralLinearGroup.ofLinearEquiv,
      LinearEquiv.funCongrLeft_apply, LinearMap.funLeft]
  map_mul' g h := by
    apply Units.ext
    ext f x
    simp [LinearMap.GeneralLinearGroup.ofLinearEquiv,
      LinearEquiv.funCongrLeft_apply, LinearMap.funLeft, mul_assoc]

@[simp] theorem branchPermutationRepresentation_apply (g : G) (f : G → k) (x : G) :
    ((branchPermutationRepresentation k G g).val f) x = f (x * g) := rfl

/-- The actual vector attached to a multiplicative scalar character. -/
def branchCharacterVector (χ : G →* kˣ) : G → k := fun x => χ x

theorem branchCharacterVector_ne_zero (χ : G →* kˣ) :
    branchCharacterVector k G χ ≠ 0 := by
  intro h
  have h1 := congrFun h 1
  simp [branchCharacterVector] at h1

theorem branchCharacterVector_eigen (χ : G →* kˣ) (g : G) :
    (branchPermutationRepresentation k G g).val (branchCharacterVector k G χ) =
      (χ g : k) • branchCharacterVector k G χ := by
  ext x
  simp [branchCharacterVector, mul_comm]

theorem branchCharacterVector_not_fixed (χ : G →* kˣ) (g : G) (hg : χ g ≠ 1) :
    (branchPermutationRepresentation k G g).val (branchCharacterVector k G χ) ≠
      branchCharacterVector k G χ := by
  intro h
  apply hg
  apply Units.ext
  simpa [branchCharacterVector] using congrFun h 1

end BranchPermutation

section CyclicBranches

variable {k : Type*} [Field k] {e : ℕ}

/-- The concrete cyclic group indexing the ramified branches. -/
abbrev CyclicBranches (e : ℕ) := Multiplicative (ZMod e)

theorem cyclicBranches_card (e : ℕ) [NeZero e] : Fintype.card (CyclicBranches e) = e := by
  simp [CyclicBranches]

/-- The character generated by an actual primitive root. -/
def cyclicBranchCharacter (ζ : kˣ) (hζ : IsPrimitiveRoot ζ e) :
    CyclicBranches e →* kˣ where
  toFun g := (hζ.zmodEquivZPowers g.toAdd).toMul.val
  map_one' := by
    change (hζ.zmodEquivZPowers (0 : ZMod e)).toMul.val = 1
    rw [map_zero]
    rfl
  map_mul' g h := by
    change (hζ.zmodEquivZPowers (g.toAdd + h.toAdd)).toMul.val = _
    rw [map_add]
    rfl

theorem cyclicBranchCharacter_nat (ζ : kˣ) (hζ : IsPrimitiveRoot ζ e) (j : ℕ) :
    cyclicBranchCharacter ζ hζ (Multiplicative.ofAdd (j : ZMod e)) = ζ ^ j := by
  change (hζ.zmodEquivZPowers (j : ZMod e)).toMul.val = ζ ^ j
  rw [hζ.zmodEquivZPowers_apply_coe_nat]
  rfl

theorem cyclicBranchCharacter_generator (ζ : kˣ) (hζ : IsPrimitiveRoot ζ e) :
    cyclicBranchCharacter ζ hζ (Multiplicative.ofAdd (1 : ZMod e)) = ζ := by
  simpa using cyclicBranchCharacter_nat ζ hζ 1

theorem cyclicBranchCharacter_val [NeZero e] (ζ : kˣ) (hζ : IsPrimitiveRoot ζ e)
    (j : ZMod e) : cyclicBranchCharacter ζ hζ (Multiplicative.ofAdd j) = ζ ^ j.val := by
  simpa using cyclicBranchCharacter_nat ζ hζ j.val

/-- The vector is literally the root-of-unity power vector, including its
value 1 at the identity branch. -/
theorem cyclicBranchCharacterVector_formula [NeZero e] (ζ : kˣ)
    (hζ : IsPrimitiveRoot ζ e) (j : ZMod e) :
    branchCharacterVector k (CyclicBranches e) (cyclicBranchCharacter ζ hζ)
      (Multiplicative.ofAdd j) = (ζ : k) ^ j.val := by
  simp only [branchCharacterVector, cyclicBranchCharacter_val, Units.val_pow_eq_pow_val]

/-- An actual nontrivial character and its actual nonzero common eigenvector
in the cyclic branch permutation representation. -/
theorem cyclicBranches_has_nontrivial_eigenvector [IsAlgClosed k]
    (he : 1 < e) (heK : (e : k) ≠ 0) :
    ∃ (ζ : kˣ) (hζ : IsPrimitiveRoot ζ e) (χ : CyclicBranches e →* kˣ)
      (f : CyclicBranches e → k),
      χ = cyclicBranchCharacter ζ hζ ∧
      f ≠ 0 ∧
      (∀ j : ZMod e, f (Multiplicative.ofAdd j) = (ζ : k) ^ j.val) ∧
      (∀ g, (branchPermutationRepresentation k (CyclicBranches e) g).val f = (χ g : k) • f) ∧
      χ (Multiplicative.ofAdd (1 : ZMod e)) ≠ 1 ∧
      (branchPermutationRepresentation k (CyclicBranches e)
        (Multiplicative.ofAdd (1 : ZMod e))).val f ≠ f := by
  let : NeZero e := ⟨by omega⟩
  let : NeZero (e : k) := ⟨heK⟩
  obtain ⟨a, ha⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot k e
  let ζ : kˣ := (ha.isUnit (NeZero.ne e)).unit
  have hζ : IsPrimitiveRoot ζ e := ha.isUnit_unit (NeZero.ne e)
  let χ := cyclicBranchCharacter ζ hζ
  have hχ : χ (Multiplicative.ofAdd (1 : ZMod e)) ≠ 1 := by
    rw [cyclicBranchCharacter_generator]
    exact hζ.ne_one he
  exact ⟨ζ, hζ, χ, branchCharacterVector k (CyclicBranches e) χ, rfl,
    branchCharacterVector_ne_zero k (CyclicBranches e) χ,
    cyclicBranchCharacterVector_formula ζ hζ,
    branchCharacterVector_eigen k (CyclicBranches e) χ,
    hχ, branchCharacterVector_not_fixed k (CyclicBranches e) χ _ hχ⟩

end CyclicBranches

section ScalarTwists

variable {k G V : Type*} [Field k] [Group G]
  [AddCommGroup V] [Module k V] [Nontrivial V]

/-- Scalar multiplication can be cancelled on an actual invertible
endomorphism of a nonzero vector space. -/
theorem scalarTwist_eq_iff (A : LinearMap.GeneralLinearGroup k V) (a b : kˣ) :
    (a : k) • A.val = (b : k) • A.val ↔ a = b := by
  constructor
  · intro h
    obtain ⟨v, hv⟩ := exists_ne (0 : V)
    have hAv : A.val v ≠ 0 := by
      intro hz
      apply hv
      exact A.toLinearEquiv.injective (by simpa using hz)
    apply Units.ext
    apply smul_left_injective k hAv
    exact congrArg (fun F : V →ₗ[k] V => F v) h
  · rintro rfl
    rfl

/-- Two actual scalar twists that are trivial on a subgroup have the same
scalar character there. No tensor constituent is needed. -/
theorem scalarTwists_trivial_on_subgroup_unique
    (ρ : G →* LinearMap.GeneralLinearGroup k V) (χ₁ χ₂ : G →* kˣ)
    (W : Subgroup G)
    (h₁ : ∀ g ∈ W, (χ₁ g : k) • (ρ g).val = LinearMap.id)
    (h₂ : ∀ g ∈ W, (χ₂ g : k) • (ρ g).val = LinearMap.id) :
    ∀ g ∈ W, χ₁ g = χ₂ g := by
  intro g hg
  exact (scalarTwist_eq_iff (ρ g) (χ₁ g) (χ₂ g)).mp ((h₁ g hg).trans (h₂ g hg).symm)

theorem scalarTwists_restrictions_eq
    (ρ : G →* LinearMap.GeneralLinearGroup k V) (χ₁ χ₂ : G →* kˣ)
    (W : Subgroup G)
    (h₁ : ∀ g ∈ W, (χ₁ g : k) • (ρ g).val = LinearMap.id)
    (h₂ : ∀ g ∈ W, (χ₂ g : k) • (ρ g).val = LinearMap.id) :
    χ₁.comp W.subtype = χ₂.comp W.subtype := by
  apply MonoidHom.ext
  intro g
  exact scalarTwists_trivial_on_subgroup_unique ρ χ₁ χ₂ W h₁ h₂ g.val g.property

end ScalarTwists

end PrimeGap182.TypeIII

#print axioms PrimeGap182.TypeIII.branchCharacterVector_eigen
#print axioms PrimeGap182.TypeIII.cyclicBranchCharacterVector_formula
#print axioms PrimeGap182.TypeIII.cyclicBranches_has_nontrivial_eigenvector
#print axioms PrimeGap182.TypeIII.scalarTwist_eq_iff
#print axioms PrimeGap182.TypeIII.scalarTwists_trivial_on_subgroup_unique
#print axioms PrimeGap182.TypeIII.scalarTwists_restrictions_eq
