import TypeIIISelectedGram

/-! The public selected-factor Cauchy theorem applied to the actual signed
profile mass. The Gram equality is discharged by the proved finite expansion;
it is not an application premise. Generated by scripts/build_selected_cauchy.py. -/

open scoped BigOperators Classical
open PrimeGap186 UniqueFactorizationMonoid

namespace PrimeGap182.TypeIII

noncomputable section

set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option maxHeartbeats 1500000

theorem selected_factor_cauchy_profile_bound
    (b : ℕ+) (b₁ b₂ b₃ : ℕ)
    (hb₁ : 0 < b₁) (hb₂ : 0 < b₂) (hb₃ : 0 < b₃)
    (hb : (b : ℕ) = (radical (b₁ * b₂ * b₃) : ℕ))
    (D : Finset ℕ+) (hD : ∀ d ∈ D, Squarefree ((b : ℕ) * (d : ℕ)))
    (ρ σ : ℕ+ → ℕ+) (hfactor : ∀ d ∈ D, d = ρ d * σ d)
    (a₀ : ℤ) (a : ∀ d : ℕ+, (ZMod ((b : ℕ) * (d : ℕ)))ˣ)
    (ha : ∀ d ∈ D,
      (a d : ZMod ((b : ℕ) * (d : ℕ))) = (a₀ : ZMod ((b : ℕ) * (d : ℕ))))
    (M : Finset ℤ) (η : ℕ → ℂ) (α : ℤ → ℂ)
    (N : ℕ) (hM : M ⊆ Finset.Ico 1 (1 + (N : ℤ)))
    (x H ε Tψ : ℝ) (hx : 0 < x) (hH : 0 < H) (hTψ : 1 ≤ Tψ)
    (ψ : ℝ → ℝ) (hψnonneg : ∀ t : ℝ, 0 ≤ ψ t)
    (hψone : ∀ t ∈ Set.Icc (-1 : ℝ) 1, ψ t = 1)
    (hψsupport : Function.support ψ ⊆ Set.Icc (-Tψ) Tψ) :
    let Hb : ℝ := x ^ (3 * ε / 2) * H / ((b₁ * b₂ * b₃ : ℕ) : ℝ)
    let L : Finset ℤ :=
      (Finset.Icc (Int.ceil (-Hb)) (Int.floor Hb)).filter (fun ℓ => ℓ ≠ 0)
    let E : Finset ℤ := Finset.Icc (Int.ceil (-Tψ * Hb)) (Int.floor (Tψ * Hb))
    let 𝒮 : Finset ℕ+ := D.image σ
    let ℛ : ℕ+ → Finset ℕ+ := fun s => (D.filter (fun d => σ d = s)).image ρ
    let τ₃ : ℤ → ℝ := fun ℓ =>
      (((ArithmeticFunction.zeta : ArithmeticFunction ℕ) ^ 3) ℓ.natAbs : ℝ)
    let P : ℕ := ∏ d ∈ D, (d : ℕ)
    let c : ZMod P := (a₀ : ZMod P) * ((b₁ * b₂ * b₃ : ℕ) : ZMod P) *
      (((b : ℕ) : ZMod P)⁻¹) ^ 3
    let A : ℤ := (c.val : ℤ)
    let A_d : ∀ d : ℕ+, (ZMod (d : ℕ))ˣ := fun d =>
      Units.map ((ZMod.castHom (Nat.dvd_mul_left (d : ℕ) (b : ℕ))
        (ZMod (d : ℕ))).toMonoidHom) (a d)
    let K : ℤ → ℂ := fun ℓ =>
      ∑ d ∈ D, if Int.gcd (((b : ℕ) : ℤ) * ℓ) ((d : ℕ) : ℤ) = 1 then
        η ((b : ℕ) * (d : ℕ)) *
          ∑ m ∈ M, if Int.gcd m (((b : ℕ) * (d : ℕ) : ℕ) : ℤ) = 1 then
            α m * normalizedKloosterman3Mod (d : ℕ)
              ((A_d d : ZMod (d : ℕ)) * ((b₁ * b₂ * b₃ : ℕ) : ZMod (d : ℕ)) *
                (ℓ : ZMod (d : ℕ)) * (m : ZMod (d : ℕ))⁻¹ *
                (((b : ℕ) : ZMod (d : ℕ))⁻¹) ^ 3)
          else 0
      else 0
    let F : ℕ+ → ℤ → ℂ := fun s ℓ =>
      ∑ r ∈ ℛ s,
        if Int.gcd (((b : ℕ) : ℤ) * ℓ) (((r : ℕ) * (s : ℕ) : ℕ) : ℤ) = 1 then
          η ((b : ℕ) * (r : ℕ) * (s : ℕ)) *
            ∑ m ∈ M,
              if Int.gcd m (((b : ℕ) * (r : ℕ) * (s : ℕ) : ℕ) : ℤ) = 1 then
                α m * normalizedKloosterman3Mod ((r : ℕ) * (s : ℕ))
                  (((A : ZMod ((r : ℕ) * (s : ℕ))) *
                    (m : ZMod ((r : ℕ) * (s : ℕ)))⁻¹) *
                    (ℓ : ZMod ((r : ℕ) * (s : ℕ))))
              else 0
        else 0
    let U : ℕ+ → ℕ+ → ℕ+ → ℤ → ℤ → ℂ := fun r₁ r₂ s m₁ m₂ =>
      ∑ ℓ ∈ E,
        if IsUnit (ℓ : ZMod ((s : ℕ) * Nat.lcm (r₁ : ℕ) (r₂ : ℕ))) then
          (ψ ((ℓ : ℝ) / Hb) : ℂ) *
            normalizedKloosterman3Mod ((r₁ : ℕ) * (s : ℕ))
              (((A : ZMod ((r₁ : ℕ) * (s : ℕ))) *
                (m₁ : ZMod ((r₁ : ℕ) * (s : ℕ)))⁻¹) *
                (ℓ : ZMod ((r₁ : ℕ) * (s : ℕ)))) *
            star (normalizedKloosterman3Mod ((r₂ : ℕ) * (s : ℕ))
              (((A : ZMod ((r₂ : ℕ) * (s : ℕ))) *
                (m₂ : ZMod ((r₂ : ℕ) * (s : ℕ)))⁻¹) *
                (ℓ : ZMod ((r₂ : ℕ) * (s : ℕ)))))
        else 0
    let T₁ : ℝ := ∑ s ∈ 𝒮, (1 / (s : ℝ)) * ∑ ℓ ∈ L, τ₃ ℓ ^ 2
    let T₂ : ℝ := ∑ s ∈ 𝒮, ∑ ℓ ∈ E, (s : ℝ) * ψ ((ℓ : ℝ) / Hb) * ‖F s ℓ‖ ^ 2
    let G₂ : ℂ := ∑ s ∈ 𝒮, ∑ r₁ ∈ ℛ s, ∑ r₂ ∈ ℛ s, ∑ m₁ ∈ M, ∑ m₂ ∈ M,
      if Int.gcd m₁ (((b : ℕ) * (r₁ : ℕ) * (s : ℕ) : ℕ) : ℤ) = 1 ∧
          Int.gcd m₂ (((b : ℕ) * (r₂ : ℕ) * (s : ℕ) : ℕ) : ℤ) = 1 then
        (s : ℂ) *
          (η ((b : ℕ) * (r₁ : ℕ) * (s : ℕ)) *
            star (η ((b : ℕ) * (r₂ : ℕ) * (s : ℕ)))) *
          (α m₁ * star (α m₂)) * U r₁ r₂ s m₁ m₂
      else 0
    0 ≤ T₁ ∧ 0 ≤ T₂ ∧ (T₂ : ℂ) = G₂ ∧
      T₂ ≤ selectedProfileMass (b : ℕ) 𝒮 ℛ A M η α N Tψ Hb ψ ∧
      (∑ ℓ ∈ L, τ₃ ℓ * ‖K ℓ‖) ^ 2 ≤
        T₁ * selectedProfileMass (b : ℕ) 𝒮 ℛ A M η α N Tψ Hb ψ ∧
      ∀ s ∈ 𝒮, ∀ r₁ ∈ ℛ s, ∀ r₂ ∈ ℛ s,
        r₁ * s ∈ D ∧ r₂ * s ∈ D ∧
        Squarefree (s : ℕ) ∧ Squarefree (r₁ : ℕ) ∧ Squarefree (r₂ : ℕ) ∧
        Nat.Coprime (s : ℕ) ((r₁ : ℕ) * (r₂ : ℕ)) ∧
        IsUnit (A : ZMod ((s : ℕ) * Nat.lcm (r₁ : ℕ) (r₂ : ℕ))) := by
  intro Hb L E 𝒮 ℛ τ₃ P c A A_d K F U T₁ T₂ G₂
  have hp := typeIII_selected_factor_cauchy_correlation b b₁ b₂ b₃ hb₁ hb₂ hb₃ hb
    D hD ρ σ hfactor a₀ a ha M η α x H ε Tψ hx hH hTψ ψ hψnonneg hψone hψsupport
  obtain ⟨_, _, _, _, _, _, hT₁, hT₂, hCS, hGram, _, _, hparts⟩ := hp
  have hGram' : (T₂ : ℂ) = selectedSignedGram (b : ℕ) 𝒮 ℛ A M η α Tψ Hb ψ := by
    calc
      _ = G₂ := hGram
      _ = _ := (selectedSignedGram_expansion (b : ℕ) 𝒮 ℛ A M η α Tψ Hb ψ).symm
  have hmass := selected_T2_le_profileMass (b : ℕ) 𝒮 ℛ A M η α N hM Tψ Hb ψ T₂ hT₂ hGram'
  exact ⟨hT₁, hT₂, hGram, hmass, hCS.trans (mul_le_mul_of_nonneg_left hmass hT₁), hparts⟩

#print axioms selected_factor_cauchy_profile_bound

end

end PrimeGap182.TypeIII
