import TypeIIISampledFineBand

/-!
# Global positive smooth Type III convolution discrepancy

The actual positive compact profile sequences, finite convolution, coherent
primitive residue, and full finite set of dense squarefree moduli are retained
from the public source. The new local Fourier input is explicit; sampling,
fine-band covering, divisor growth, and every analytic saving are proved.
Generated by scripts/build_type_iii_positive_global.py.
-/

open scoped BigOperators Classical ContDiff NNReal
open PrimeGap186 PrimeGap182Audit UniqueFactorizationMonoid

namespace PrimeGap182.TypeIII

noncomputable section

set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option maxHeartbeats 4000000

theorem LocalFourierHypothesis.positive_smooth_convolution_global_log_saving
    {C₀ : ℝ} (hC₀ : 0 ≤ C₀) {D₀ p₀ : ℕ} (hlocal : LocalFourierHypothesis C₀ D₀ p₀)
    (omegaExp δ σ C E Eα : ℝ) (D : ℕ)
    (hω : 0 < omegaExp) (hδ : 0 < δ) (hC : 1 ≤ C) (hσupper : σ < 1 / 6)
    (hσ : 1 / 30 + 56 * omegaExp / 15 + 4 * δ / 15 < σ)
    (hswitch : 1 < 108 * omegaExp + 2 * δ) :
    let μ : ℝ := typeIIIMu σ
    let θ : ℝ := typeIIITheta omegaExp
    let εcap : ℝ := typeIIIEpsilonCap μ θ δ
    0 < εcap ∧
      ∀ ε : ℝ, 0 < ε → ε ≤ εcap →
      let κ : ℝ := ε / 4
      let J : ℕ := Nat.ceil (22 / ε)
      ∀ A : ℝ, 0 < A →
      ∃ K X : ℝ, 0 < K ∧ Real.exp 1 ≤ X ∧
      ∀ x : ℝ, X ≤ x →
      ∀ M N₁ N₂ N₃ : ℝ, 1 ≤ M → 1 ≤ N₁ → 1 ≤ N₂ → 1 ≤ N₃ →
        let N : ℝ := N₁ * N₂ * N₃
        x / C ≤ M * N → M * N ≤ C * x →
        x ^ (1 / 2 + σ - κ) / C ≤ N₁ * N₂ →
        x ^ (1 / 2 + σ - κ) / C ≤ N₁ * N₃ →
        x ^ (1 / 2 + σ - κ) / C ≤ N₂ * N₃ →
        N₁ ≤ C * x ^ (1 / 2 - σ + κ) →
        N₂ ≤ C * x ^ (1 / 2 - σ + κ) →
        N₃ ≤ C * x ^ (1 / 2 - σ + κ) →
      ∀ Y : Set.Ici (1 : ℝ), (Y : ℝ) = x ^ δ →
      ∀ Qset : Finset ℕ+,
        (∀ q ∈ Qset,
          Squarefree (q : ℕ) ∧
          Nonempty (DenseDivisibilityWitness Y 1 (q : ℕ)) ∧
          (q : ℝ) ≤ C * x ^ (1 / 2 + 2 * omegaExp + κ)) →
      ∀ Lα L₁ L₂ L₃ : ℝ, 0 ≤ Lα → 0 ≤ L₁ → 0 ≤ L₂ → 0 ≤ L₃ →
      ∀ α : ℕ →₀ ℂ,
        (∀ n ∈ α.support, M / C ≤ (n : ℝ) ∧ (n : ℝ) ≤ C * M) →
        (∀ n ∈ α.support,
          ‖α n‖ ≤ Lα * ((Nat.divisors n).card : ℝ) ^ D * (Real.log x) ^ Eα) →
      ∀ ψ₁ ψ₂ ψ₃ : ℝ → ℂ,
        ContDiff ℝ ∞ ψ₁ → ContDiff ℝ ∞ ψ₂ → ContDiff ℝ ∞ ψ₃ →
        Function.support ψ₁ ⊆ Set.Icc (1 / C) C →
        Function.support ψ₂ ⊆ Set.Icc (1 / C) C →
        Function.support ψ₃ ⊆ Set.Icc (1 / C) C →
        (∀ r : ℕ, r ≤ J + 2 → ∀ t : ℝ,
          ‖iteratedDeriv r ψ₁ t‖ ≤ L₁ * (Real.log x) ^ E) →
        (∀ r : ℕ, r ≤ J + 2 → ∀ t : ℝ,
          ‖iteratedDeriv r ψ₂ t‖ ≤ L₂ * (Real.log x) ^ E) →
        (∀ r : ℕ, r ≤ J + 2 → ∀ t : ℝ,
          ‖iteratedDeriv r ψ₃ t‖ ≤ L₃ * (Real.log x) ^ E) →
        let β₁ : ℕ →₀ ℂ :=
          positiveCompactProfileSequence ψ₁ C N₁ 0
        let β₂ : ℕ →₀ ℂ :=
          positiveCompactProfileSequence ψ₂ C N₂ 0
        let β₃ : ℕ →₀ ℂ :=
          positiveCompactProfileSequence ψ₃ C N₃ 0
        let f : ℕ →₀ ℂ := finiteConvolution α
          (finiteConvolution β₁
            (finiteConvolution β₂ β₃))
        ∀ a₀ : ℤ,
          (∀ q ∈ Qset, IsUnit (a₀ : ZMod (q : ℕ))) →
          ∑ q ∈ Qset,
            ‖(∑ n ∈ f.support,
                if (n : ZMod (q : ℕ)) = (a₀ : ZMod (q : ℕ)) then f n else 0) -
              ((q : ℕ).totient : ℂ)⁻¹ *
                (∑ n ∈ f.support, if Nat.Coprime n (q : ℕ) then f n else 0)‖ ≤
            K * (Lα * L₁ * L₂ * L₃) * x / (Real.log x) ^ A := by
  have hCpos : 0 < C := zero_lt_one.trans_le hC
  have hCtwo : 1 ≤ C ^ 2 := one_le_pow₀ hC
  have hphys := hlocal.sampled_convolution_fineBand_discrepancy hC₀
    omegaExp δ σ (C ^ 2) C E hω hδ hCtwo hCpos.le hσupper hσ hswitch
  dsimp only at hphys ⊢
  refine ⟨hphys.1, ?_⟩
  intro ε hε hεcap A hA
  have hεsmall : ε ≤ 1 / 100 := by
    have hh : ε ≤ 1 / 1000 := hεcap.trans (min_le_left _ _)
    linarith only [hh]
  have hσsmall : 1 / 18 < σ := by linarith only [hσ, hswitch, hδ]
  have hscaleExp : 0 < 2 * σ - ε := by linarith only [hσsmall, hεsmall]
  let κ : ℝ := ε / 4
  let aExp : ℝ := 1 / 2 + 2 * omegaExp + κ
  have haExp : 0 < aExp := by dsimp [aExp, κ]; positivity
  obtain ⟨Kp, Xp, hKp, _, hp⟩ := hphys.2 ε hε hεcap
  clear hphys
  obtain ⟨Cd, hCd, hdivisor⟩ :=
    exists_divisorPower_bound D (by positivity : 0 < ε / 8)
  let Kα : ℝ := Cd * C ^ (ε / 4)
  have hKα : 0 < Kα := mul_pos hCd (Real.rpow_pos_of_pos hCpos _)
  let Acov : ℝ := 1 + 2 * Real.log C + 2 * aExp
  have hlogC : 0 ≤ Real.log C := Real.log_nonneg hC
  have hAcov : 0 < Acov := by dsimp [Acov]; positivity
  have hexp1 : 1 ≤ Real.exp 1 := Real.one_le_exp (by norm_num)
  have hlogPower (b e : ℝ) (he : 0 < e) :
      ∀ᶠ x : ℝ in Filter.atTop, (Real.log x) ^ b ≤ x ^ e := by
    clear * - hexp1 he
    filter_upwards [Filter.eventually_ge_atTop (Real.exp 1),
      (isLittleO_log_rpow_rpow_atTop b he).bound (by norm_num : (0 : ℝ) < 1)]
      with x hx hb
    have hx1 : 1 ≤ x := hexp1.trans hx
    simpa only [Real.norm_of_nonneg (Real.rpow_nonneg (Real.log_nonneg hx1) b),
      Real.norm_of_nonneg (Real.rpow_nonneg (zero_le_one.trans hx1) e), one_mul] using hb
  have hevent : ∀ᶠ x : ℝ in Filter.atTop,
      Real.exp 1 ≤ x ∧ Xp ≤ x ∧
      8 * C ^ 2 ≤ x ^ (2 * σ - ε) ∧
      C ^ 2 * x ^ (-ε) ≤ 1 / 3 ∧
      (Real.log x) ^ Eα ≤ x ^ (ε / 8) ∧
      Real.log x ≤ x ^ (ε / 4) ∧
      (Real.log x) ^ A ≤ x ^ (ε / 2) := by
    filter_upwards [Filter.eventually_ge_atTop (Real.exp 1),
      Filter.eventually_ge_atTop Xp,
      (tendsto_rpow_atTop hscaleExp).eventually_ge_atTop (8 * C ^ 2),
      ((tendsto_rpow_neg_atTop hε).const_mul (C ^ 2)).eventually_le_const
        (by norm_num : C ^ 2 * 0 < (1 : ℝ) / 3),
      hlogPower Eα (ε / 8) (by positivity),
      hlogPower 1 (ε / 4) (by positivity),
      hlogPower A (ε / 2) (by positivity)] with x hx hp hxscale hρ hαlog hlog hlogA
    exact ⟨hx, hp, hxscale, hρ, hαlog, by simpa only [Real.rpow_one] using hlog, hlogA⟩
  obtain ⟨X, hX⟩ := Filter.eventually_atTop.mp hevent
  let K : ℝ := 1 + 2 * Kp * Acov * Kα * C ^ 2
  refine ⟨K, max X (Real.exp 1), by dsimp [K]; positivity, le_max_right _ _, ?_⟩
  intro x hx M N₁ N₂ N₃ hM hN₁ hN₂ hN₃
    hMNlo hMNhi h₁₂ h₁₃ h₂₃ hN₁hi hN₂hi hN₃hi
    Y hY Qset hQset Lα L₁ L₂ L₃ hLα hL₁ hL₂ hL₃ α hαsupport hαbound
    ψ₁ ψ₂ ψ₃ hψ₁ hψ₂ hψ₃ hs₁ hs₂ hs₃ hd₁ hd₂ hd₃ a₀ ha₀
  obtain ⟨hxexp, hxXp, hxscale, hρupper, hαlog, hlogsmall, hlogA⟩ :=
    hX x ((le_max_left _ _).trans hx)
  have hx1 : 1 ≤ x := hexp1.trans hxexp
  have hx0 : 0 < x := zero_lt_one.trans_le hx1
  have hxlog : 1 ≤ Real.log x := by
    simpa only [Real.log_exp] using Real.log_le_log (Real.exp_pos 1) hxexp
  have hlog0 : 0 < Real.log x := zero_lt_one.trans_le hxlog
  have hM0 : 0 < M := zero_lt_one.trans_le hM
  have hN₁0 : 0 < N₁ := zero_lt_one.trans_le hN₁
  have hN₂0 : 0 < N₂ := zero_lt_one.trans_le hN₂
  have hN₃0 : 0 < N₃ := zero_lt_one.trans_le hN₃
  let N : ℝ := N₁ * N₂ * N₃
  have hN : 1 ≤ N :=
    one_le_mul_of_one_le_of_one_le
      (one_le_mul_of_one_le_of_one_le hN₁ hN₂) hN₃
  have hN0 : 0 < N := zero_lt_one.trans_le hN
  have hMhi : M ≤ C * x :=
    (le_mul_of_one_le_right hM0.le hN).trans hMNhi
  have hscale (U V : ℝ) (hU : 0 ≤ U)
      (huv : x ^ (1 / 2 + σ - κ) / C ≤ U * V)
      (hv : V ≤ C * x ^ (1 / 2 - σ + κ)) :
      8 * x ^ (ε / 2) ≤ U := by
    clear * - hU huv hv hCpos hx0 hxscale κ
    have hpow : x ^ (1 / 2 + σ - κ) =
        x ^ (1 / 2 - σ + κ) * x ^ (2 * σ - 2 * κ) := by
      rw [← Real.rpow_add hx0]
      congr 1
      ring
    have hl : x ^ (1 / 2 - σ + κ) * x ^ (2 * σ - 2 * κ) ≤
        x ^ (1 / 2 - σ + κ) * (C ^ 2 * U) := by
      calc
        _ = x ^ (1 / 2 + σ - κ) := hpow.symm
        _ ≤ U * V * C := (div_le_iff₀ hCpos).mp huv
        _ ≤ U * (C * x ^ (1 / 2 - σ + κ)) * C := by gcongr
        _ = _ := by ring
    have hslot : x ^ (2 * σ - 2 * κ) ≤ C ^ 2 * U :=
      (mul_le_mul_iff_right₀ (Real.rpow_pos_of_pos hx0 _)).mp hl
    have hlarge : (8 * x ^ (ε / 2)) * C ^ 2 ≤ x ^ (2 * σ - 2 * κ) := by
      calc
        _ = (8 * C ^ 2) * x ^ (ε / 2) := by ring
        _ ≤ x ^ (2 * σ - ε) * x ^ (ε / 2) := by gcongr
        _ = _ := by rw [← Real.rpow_add hx0]; congr 1; dsimp [κ]; ring
    exact (mul_le_mul_iff_left₀ (sq_pos_of_pos hCpos)).mp (by
      simpa only [mul_comm (C ^ 2) U] using hlarge.trans hslot)
  have hlarge₁ : 8 * x ^ (ε / 2) ≤ N₁ :=
    hscale N₁ N₂ hN₁0.le h₁₂ hN₂hi
  have hlarge₂ : 8 * x ^ (ε / 2) ≤ N₂ :=
    hscale N₂ N₁ hN₂0.le (by simpa only [mul_comm] using h₁₂) hN₁hi
  have hlarge₃ : 8 * x ^ (ε / 2) ≤ N₃ :=
    hscale N₃ N₁ hN₃0.le (by simpa only [mul_comm] using h₁₃) hN₁hi
  have hNlower : x ^ (3 / 4 + 3 * σ / 2 - ε) / C ^ 2 ≤ N := by
    clear * - κ h₁₂ h₁₃ h₂₃ hN₁0 hN₂0 hN₃0 hx0 hx1 hC hCpos hε hN0
    let u : ℝ := x ^ (1 / 2 + σ - κ) / C
    have hu : 0 ≤ u := by dsimp [u]; positivity
    have hpairs : u ^ 3 ≤ N ^ 2 := by
      have ht := mul_le_mul
        (mul_le_mul h₁₂ h₁₃ hu (by positivity)) h₂₃ hu (by positivity)
      calc
        u ^ 3 = u * u * u := by ring
        _ ≤ (N₁ * N₂) * (N₁ * N₃) * (N₂ * N₃) := ht
        _ = N ^ 2 := by dsimp only [N]; ring
    apply (sq_le_sq₀ (by positivity) hN0.le).mp
    calc
      (x ^ (3 / 4 + 3 * σ / 2 - ε) / C ^ 2) ^ 2 =
          x ^ ((3 / 4 + 3 * σ / 2 - ε) * (2 : ℝ)) / C ^ 4 := by
        rw [div_pow, ← Real.rpow_mul_natCast hx0.le]
        norm_num
        ring
      _ ≤ x ^ ((1 / 2 + σ - κ) * (3 : ℝ)) / C ^ 3 := by
        apply div_le_div₀ (Real.rpow_nonneg hx0.le _)
          (Real.rpow_le_rpow_of_exponent_le hx1 ?_) (by positivity) ?_
        · dsimp [κ]
          linarith
        · exact pow_le_pow_right₀ hC (by norm_num)
      _ = u ^ 3 := by
        dsimp only [u]
        rw [div_pow, ← Real.rpow_mul_natCast hx0.le]
        norm_num
      _ ≤ N ^ 2 := hpairs
  have hMphys : 1 ≤ C * M := one_le_mul_of_one_le_of_one_le hC hM
  have hMNphyslo : x / C ^ 2 ≤ (C * M) * N := by
    calc
      _ ≤ x / C := div_le_div_of_nonneg_left hx0.le hCpos (le_self_pow₀ hC two_ne_zero)
      _ ≤ M * N := hMNlo
      _ ≤ (C * M) * N := by gcongr; exact le_mul_of_one_le_left hM0.le hC
  have hMNphyshi : (C * M) * N ≤ C ^ 2 * x := by
    calc
      _ = C * (M * N) := by ring
      _ ≤ C * (C * x) := by gcongr
      _ = _ := by ring
  let M₀ : ℤ := Int.ceil (M / C)
  let M₁ : ℤ := Int.floor (C * M)
  let I : Finset ℤ := Finset.Icc M₀ M₁
  have hM₀ : 0 < M₀ := Int.ceil_pos.mpr (div_pos hM0 hCpos)
  have hwidth : (M₁ : ℝ) - (M₀ : ℝ) ≤ C * M :=
    (sub_le_self (M₁ : ℝ) (show 0 ≤ (M₀ : ℝ) by exact_mod_cast hM₀.le)).trans
      (Int.floor_le _)
  have hmark (m : ℤ) (hm : m ∈ I) :
      0 < m ∧ (m : ℝ) ≤ C * M := by
    have hi : (m : ℝ) ∈ Set.Icc (M / C) (C * M) :=
      Int.cast_mem_Icc_iff.mpr hm
    exact ⟨Int.cast_pos.mp ((div_pos hM0 hCpos).trans_le hi.1), hi.2⟩
  have hheight : ∀ m ∈ I, |(m : ℝ)| ≤ C ^ 2 * (C * M) := by
    intro m hm
    have hz : 0 ≤ (m : ℝ) := by exact_mod_cast (hmark m hm).1.le
    rw [abs_of_nonneg hz]
    exact (hmark m hm).2.trans
      (le_mul_of_one_le_left (mul_nonneg hCpos.le hM0.le) hCtwo)
  let Wα : ℝ := Kα * Lα * x ^ (ε / 4)
  have hWα : 0 ≤ Wα := by dsimp [Wα]; positivity
  have hαint : ∀ m ∈ I, ‖α m.toNat‖ ≤ Wα := by
    clear * - hαbound hmark hWα hdivisor hMhi hCpos hx0 hαlog hLα hCd hε hlog0 Kα Wα
    intro m hm
    by_cases ha : α m.toNat = 0
    · simpa only [ha, norm_zero] using hWα
    have hn : m.toNat ≠ 0 := (Int.pos_iff_toNat_pos.mp (hmark m hm).1).ne'
    have hnreal : (m.toNat : ℝ) ≤ C ^ 2 * x := by
      have hcast : (m.toNat : ℝ) = (m : ℝ) := by
        exact_mod_cast Int.toNat_of_nonneg (hmark m hm).1.le
      rw [hcast]
      calc
        _ ≤ C * M := (hmark m hm).2
        _ ≤ C * (C * x) := by gcongr
        _ = _ := by ring
    have hτ : ((Nat.divisors m.toNat).card : ℝ) ^ D ≤
        Kα * x ^ (ε / 8) := by
      calc
        _ ≤ Cd * (m.toNat : ℝ) ^ (ε / 8) := hdivisor _ hn
        _ ≤ Cd * (C ^ 2 * x) ^ (ε / 8) := by gcongr
        _ = Kα * x ^ (ε / 8) := by
          rw [Real.mul_rpow (sq_nonneg C) hx0.le, ← Real.rpow_natCast_mul hCpos.le]
          dsimp only [Kα]
          norm_num only [Nat.cast_ofNat]
          rw [show (2 : ℝ) * (ε / 8) = ε / 4 by ring]
          ring
    calc
      _ ≤ Lα * ((Nat.divisors m.toNat).card : ℝ) ^ D * (Real.log x) ^ Eα :=
        hαbound _ (Finsupp.mem_support_iff.mpr ha)
      _ ≤ Lα * (Kα * x ^ (ε / 8)) * x ^ (ε / 8) := by gcongr
      _ = Wα := by
        dsimp only [Wα]
        rw [mul_assoc Lα, mul_assoc Kα, ← Real.rpow_add hx0]
        rw [show ε / 8 + ε / 8 = ε / 4 by ring]
        ring
  let ρ : ℝ := C ^ 2 * x ^ (-ε)
  let r : ℝ := 1 + ρ
  let Qmax : ℝ := C * x ^ aExp
  let label : ℕ+ → ℕ := fun q => Nat.floor (Real.logb r (q : ℝ))
  let bins : ℕ := Nat.floor (Real.logb r Qmax) + 1
  have hρ : 0 < ρ := by dsimp only [ρ]; positivity
  have hr : 1 < r := by dsimp only [r]; linarith
  have hr0 : 0 < r := zero_lt_one.trans hr
  have hQmax : 1 ≤ Qmax :=
    one_le_mul_of_one_le_of_one_le hC (Real.one_le_rpow hx1 haExp.le)
  have hQmax0 : 0 < Qmax := zero_lt_one.trans_le hQmax
  have hlabels : ∀ q ∈ Qset, label q ∈ Finset.range bins := by
    clear * - hQset hr label bins Qmax
    intro q hq
    apply Finset.mem_range.mpr
    have hq0 : 0 < (q : ℝ) := by exact_mod_cast q.pos
    have hqmax : (q : ℝ) ≤ Qmax := (hQset q hq).2.2
    have hl := Nat.floor_mono (Real.logb_le_logb_of_le hr hq0 hqmax)
    exact lt_of_le_of_lt hl (Nat.lt_succ_self _)
  have hcenter (j : ℕ) (hj : j ∈ Finset.range bins) :
      0 < r ^ j ∧ r ^ j ≤ C ^ 2 * x ^ (1 / 2 + 2 * omegaExp + ε) := by
    clear * - hj hC hx1 hr hr0 hQmax hQmax0 hε κ aExp bins Qmax
    have hj' : j ≤ Nat.floor (Real.logb r Qmax) :=
      Nat.le_of_lt_succ (Finset.mem_range.mp hj)
    have hjreal : (j : ℝ) ≤ Real.logb r Qmax :=
      (Nat.cast_le.mpr hj').trans (Nat.floor_le (Real.logb_nonneg hr hQmax))
    have hpow : r ^ j ≤ Qmax := by
      simpa only [Real.rpow_natCast] using
        (Real.le_logb_iff_rpow_le hr hQmax0).mp hjreal
    refine ⟨pow_pos hr0 _, hpow.trans ?_⟩
    dsimp only [Qmax]
    apply mul_le_mul (le_self_pow₀ hC two_ne_zero)
      (Real.rpow_le_rpow_of_exponent_le hx1 ?_) (by positivity) (sq_nonneg C)
    dsimp only [aExp, κ]
    linarith
  have hband (j : ℕ) : ∀ q ∈ Qset.filter (fun q => label q = j),
      Squarefree (q : ℕ) ∧
      Nonempty (DenseDivisibilityWitness Y 1 (q : ℕ)) ∧
      r ^ j * (1 - C ^ 2 * x ^ (-ε)) ≤ (q : ℝ) ∧
      (q : ℝ) ≤ r ^ j * (1 + C ^ 2 * x ^ (-ε)) := by
    clear * - hQset hr hr0 hρ label r ρ
    intro q hq
    obtain ⟨hqset, hlabel⟩ := Finset.mem_filter.mp hq
    have hq0 : 0 < (q : ℝ) := by exact_mod_cast q.pos
    have hq1 : 1 ≤ (q : ℝ) := by
      exact_mod_cast (show (1 : ℕ) ≤ (q : ℕ) from q.pos)
    have hlow : r ^ label q ≤ (q : ℝ) := by
      simpa only [Real.rpow_natCast] using
        (Real.le_logb_iff_rpow_le hr hq0).mp
          (Nat.floor_le (Real.logb_nonneg hr hq1))
    have hupp : (q : ℝ) < r ^ (label q + 1) := by
      rw [← Real.rpow_natCast]
      apply (Real.logb_lt_iff_lt_rpow hr hq0).mp
      simpa only [Nat.cast_add, Nat.cast_one, label] using
        Nat.lt_floor_add_one (Real.logb r (q : ℝ))
    rw [hlabel] at hlow hupp
    refine ⟨(hQset q hqset).1, (hQset q hqset).2.1, ?_, ?_⟩
    · exact (mul_le_of_le_one_right (pow_pos hr0 j).le
        (by dsimp only [ρ] at hρ; linarith)).trans hlow
    · simpa only [pow_succ, r, ρ] using hupp.le
  have hlogr : ρ / 2 ≤ Real.log r := by
    clear * - hρ hρupper r ρ
    have hρtwo : ρ ≤ 2 := by dsimp only [ρ]; linarith only [hρupper]
    calc
      ρ / 2 = 2 * ρ / 4 := by ring
      _ ≤ 2 * ρ / (ρ + 2) :=
        div_le_div_of_nonneg_left (by positivity) (by positivity) (by linarith only [hρtwo])
      _ ≤ Real.log r := Real.le_log_one_add_of_nonneg hρ.le
  have hrhoinverse : ρ⁻¹ ≤ x ^ ε := by
    clear * - hCtwo hx0 ρ
    dsimp only [ρ]
    rw [mul_inv_rev, ← Real.rpow_neg hx0.le (-ε), neg_neg]
    exact mul_le_of_le_one_right (Real.rpow_nonneg hx0.le _)
      (inv_le_one_of_one_le₀ hCtwo)
  have hbins : (bins : ℝ) ≤ Acov * x ^ ε * Real.log x := by
    clear * - hCpos hx0 hlogC haExp hxlog hx1 hε hlogr hρ hrhoinverse hr hQmax
      Qmax aExp bins Acov r ρ
    have hlogQ : Real.log Qmax = Real.log C + aExp * Real.log x := by
      dsimp only [Qmax]
      rw [Real.log_mul hCpos.ne' (Real.rpow_pos_of_pos hx0 _).ne',
        Real.log_rpow hx0]
    have hlogQupper : Real.log Qmax ≤ (Real.log C + aExp) * Real.log x := by
      rw [hlogQ, add_mul (Real.log C) aExp (Real.log x)]
      exact add_le_add (le_mul_of_one_le_right hlogC hxlog) le_rfl
    have hf : (Nat.floor (Real.logb r Qmax) : ℝ) ≤ Real.logb r Qmax :=
      Nat.floor_le (Real.logb_nonneg hr hQmax)
    have hxε : 1 ≤ x ^ ε := Real.one_le_rpow hx1 hε.le
    have hbase : 1 ≤ x ^ ε * Real.log x :=
      one_le_mul_of_one_le_of_one_le hxε hxlog
    calc
      (bins : ℝ) ≤ Real.log Qmax / Real.log r + 1 := by
        dsimp only [bins]
        push_cast
        simpa only [Real.logb] using add_le_add hf (le_refl (1 : ℝ))
      _ ≤ Real.log Qmax / (ρ / 2) + 1 := by
        gcongr
        exact Real.log_nonneg hQmax
      _ = 2 * Real.log Qmax * ρ⁻¹ + 1 := by ring
      _ ≤ 2 * ((Real.log C + aExp) * Real.log x) * x ^ ε + 1 := by
        gcongr
      _ ≤ 2 * ((Real.log C + aExp) * Real.log x) * x ^ ε +
          x ^ ε * Real.log x := add_le_add le_rfl hbase
      _ = Acov * x ^ ε * Real.log x := by
        dsimp only [Acov]
        ring
  have hαpair (F : ℤ → ℂ) :
      (∑ n ∈ α.support, α n * F (n : ℤ)) =
        ∑ m ∈ I, α m.toNat * F m := by
    clear * - hαsupport hmark I
    refine Finset.sum_bij_ne_zero (fun n _ _ => (n : ℤ)) ?_ ?_ ?_ ?_
    · intro n hn _
      apply Int.cast_mem_Icc_iff.mp
      simpa only [Set.mem_Icc, Int.cast_natCast] using hαsupport n hn
    · intro n₁ _ _ n₂ _ _ he
      exact Int.ofNat.inj he
    · intro m hm hmne
      have ha : α m.toNat ≠ 0 := left_ne_zero_of_mul hmne
      have hcast : (m.toNat : ℤ) = m := Int.toNat_of_nonneg (hmark m hm).1.le
      refine ⟨m.toNat, Finsupp.mem_support_iff.mpr ha, ?_, hcast⟩
      simpa only [hcast] using hmne
    · intro n _ _
      simp only [Int.toNat_natCast]
  have hβpair (N' : ℝ) (hN' : 0 < N') (ψ : ℝ → ℂ)
      (hs : Function.support ψ ⊆ Set.Icc (1 / C) C) (F : ℤ → ℂ) :
      let β := positiveCompactProfileSequence ψ C N' 0
      (∑ n ∈ β.support, β n * F (n : ℤ)) =
        ∑ z ∈ Finset.Icc (Int.ceil (-C * N')) (Int.floor (C * N')),
          ψ ((z : ℝ) / N') * F z := by
    clear * - hCpos hN' hs
    let s : Finset ℕ := Finset.Icc 1 (Nat.floor (C * N'))
    have hwindow (t : ℝ) (ht : ψ (t / N') ≠ 0) :
        0 < t ∧ -C * N' ≤ t ∧ t ≤ C * N' := by
      have hh := hs ht
      have hlo : (1 / C) * N' ≤ t := (le_div_iff₀ hN').mp hh.1
      have hhi : t ≤ C * N' := (div_le_iff₀ hN').mp hh.2
      have htpos : 0 < t := (mul_pos (one_div_pos.mpr hCpos) hN').trans_le hlo
      refine ⟨htpos, ?_, hhi⟩
      simpa only [neg_mul] using
        (neg_nonpos.mpr (mul_nonneg hCpos.le hN'.le)).trans htpos.le
    have hmemS (n : ℕ) (hn : ψ ((n : ℝ) / N') ≠ 0) : n ∈ s := by
      have hh := hwindow (n : ℝ) hn
      exact Finset.mem_Icc.mpr ⟨Nat.cast_pos.mp hh.1, Nat.le_floor hh.2.2⟩
    have hmemI (z : ℤ) (hz : ψ ((z : ℝ) / N') ≠ 0) :
        z ∈ Finset.Icc (Int.ceil (-C * N')) (Int.floor (C * N')) :=
      Int.cast_mem_Icc_iff.mp (hwindow (z : ℝ) hz).2
    have hnat :
        (∑ n ∈ (positiveCompactProfileSequence
          ψ C N' 0).support,
          positiveCompactProfileSequence ψ C N' 0 n *
            F (n : ℤ)) = ∑ n ∈ s, ψ ((n : ℝ) / N') * F (n : ℤ) := by
      simp only [positiveCompactProfileSequence,
        zero_add, sub_zero]
      change (∑ n ∈ s, Finsupp.single n (ψ ((n : ℝ) / N'))).sum
        (fun n z => z * F (n : ℤ)) = _
      rw [← Finsupp.indicator_eq_sum_single]
      exact Finsupp.sum_indicator_index _ (fun _ _ => zero_mul _)
    refine hnat.trans ?_
    refine Finset.sum_bij_ne_zero (fun n _ _ => (n : ℤ)) ?_ ?_ ?_ ?_
    · intro n _ hn
      apply hmemI
      simpa only [Int.cast_natCast] using
        (left_ne_zero_of_mul hn : ψ ((n : ℝ) / N') ≠ 0)
    · intro n₁ _ _ n₂ _ _ he
      exact Int.ofNat.inj he
    · intro z _ hz
      have hw : ψ ((z : ℝ) / N') ≠ 0 := left_ne_zero_of_mul hz
      have hzpos : 0 < z := by exact_mod_cast (hwindow (z : ℝ) hw).1
      lift z to ℕ using hzpos.le with n
      simp only [Int.cast_natCast] at hw hz ⊢
      exact ⟨n, hmemS _ hw, hz, rfl⟩
    · intro n _ _
      simp only [Int.cast_natCast]
  let β₁ := positiveCompactProfileSequence ψ₁ C N₁ 0
  let β₂ := positiveCompactProfileSequence ψ₂ C N₂ 0
  let β₃ := positiveCompactProfileSequence ψ₃ C N₃ 0
  let f := finiteConvolution α
    (finiteConvolution β₁
      (finiteConvolution β₂ β₃))
  let P₁ := Finset.Icc (Int.ceil (-C * N₁)) (Int.floor (C * N₁))
  let P₂ := Finset.Icc (Int.ceil (-C * N₂)) (Int.floor (C * N₂))
  let P₃ := Finset.Icc (Int.ceil (-C * N₃)) (Int.floor (C * N₃))
  let w : ℤ → ℤ → ℤ → ℤ → ℂ := fun m n₁ n₂ n₃ =>
    α m.toNat * ψ₁ ((n₁ : ℝ) / N₁) * ψ₂ ((n₂ : ℝ) / N₂) *
      ψ₃ ((n₃ : ℝ) / N₃)
  have hconv (a b : ℕ →₀ ℂ) (F : ℤ → ℂ) :
      (∑ n ∈ (finiteConvolution a b).support,
        finiteConvolution a b n * F (n : ℤ)) =
      ∑ m ∈ a.support, a m * ∑ n ∈ b.support, b n * F ((m : ℤ) * n) := by
    clear * -
    rw [finiteConvolution_pairing]
    simp only [Finset.mul_sum, mul_assoc, Nat.cast_mul]
  have hfnat (F : ℤ → ℂ) :
      (∑ n ∈ f.support, f n * F (n : ℤ)) =
      ∑ m ∈ α.support, α m *
        ∑ n₁ ∈ β₁.support, β₁ n₁ *
          ∑ n₂ ∈ β₂.support, β₂ n₂ *
            ∑ n₃ ∈ β₃.support, β₃ n₃ *
              F ((m : ℤ) * n₁ * n₂ * n₃) := by
    clear * - hconv f β₁ β₂ β₃
    dsimp only [f]
    rw [hconv α _ F]
    apply Finset.sum_congr rfl
    intro m _
    apply congrArg (fun z : ℂ => α m * z)
    rw [hconv β₁ _ (fun z => F ((m : ℤ) * z))]
    apply Finset.sum_congr rfl
    intro n₁ _
    apply congrArg (fun z : ℂ => β₁ n₁ * z)
    rw [hconv β₂ β₃ (fun z => F ((m : ℤ) * ((n₁ : ℤ) * z)))]
    simp only [mul_assoc]
  have hpair (F : ℤ → ℂ) :
      (∑ n ∈ f.support, f n * F (n : ℤ)) =
      ∑ m ∈ I, ∑ n₁ ∈ P₁, ∑ n₂ ∈ P₂, ∑ n₃ ∈ P₃,
        w m n₁ n₂ n₃ * F (m * n₁ * n₂ * n₃) := by
    clear * - hfnat hαpair hβpair hN₁0 hN₂0 hN₃0 hs₁ hs₂ hs₃ β₁ β₂ β₃ P₁ P₂ P₃ w
    rw [hfnat]
    calc
      _ = ∑ m ∈ I, α m.toNat *
          ∑ n₁ ∈ β₁.support, β₁ n₁ *
            ∑ n₂ ∈ β₂.support, β₂ n₂ *
              ∑ n₃ ∈ β₃.support, β₃ n₃ *
                F (m * (n₁ : ℤ) * n₂ * n₃) :=
        hαpair (fun m => ∑ n₁ ∈ β₁.support, β₁ n₁ *
          ∑ n₂ ∈ β₂.support, β₂ n₂ *
            ∑ n₃ ∈ β₃.support, β₃ n₃ * F (m * (n₁ : ℤ) * n₂ * n₃))
      _ = ∑ m ∈ I, α m.toNat *
          ∑ n₁ ∈ P₁, ψ₁ ((n₁ : ℝ) / N₁) *
            ∑ n₂ ∈ P₂, ψ₂ ((n₂ : ℝ) / N₂) *
              ∑ n₃ ∈ P₃, ψ₃ ((n₃ : ℝ) / N₃) *
                F (m * n₁ * n₂ * n₃) := by
        apply Finset.sum_congr rfl
        intro m _
        apply congrArg (fun z : ℂ => α m.toNat * z)
        calc
          _ = ∑ n₁ ∈ P₁, ψ₁ ((n₁ : ℝ) / N₁) *
              ∑ n₂ ∈ β₂.support, β₂ n₂ *
                ∑ n₃ ∈ β₃.support, β₃ n₃ * F (m * n₁ * (n₂ : ℤ) * n₃) :=
            hβpair N₁ hN₁0 ψ₁ hs₁ (fun n₁ => ∑ n₂ ∈ β₂.support, β₂ n₂ *
              ∑ n₃ ∈ β₃.support, β₃ n₃ * F (m * n₁ * (n₂ : ℤ) * n₃))
          _ = _ := by
            apply Finset.sum_congr rfl
            intro n₁ _
            apply congrArg (fun z : ℂ => ψ₁ ((n₁ : ℝ) / N₁) * z)
            calc
              _ = ∑ n₂ ∈ P₂, ψ₂ ((n₂ : ℝ) / N₂) *
                  ∑ n₃ ∈ β₃.support, β₃ n₃ * F (m * n₁ * n₂ * (n₃ : ℤ)) :=
                hβpair N₂ hN₂0 ψ₂ hs₂ (fun n₂ =>
                  ∑ n₃ ∈ β₃.support, β₃ n₃ * F (m * n₁ * n₂ * (n₃ : ℤ)))
              _ = _ := by
                apply Finset.sum_congr rfl
                intro n₂ _
                exact congrArg (fun z : ℂ => ψ₂ ((n₂ : ℝ) / N₂) * z)
                  (hβpair N₃ hN₃0 ψ₃ hs₃ (fun n₃ => F (m * n₁ * n₂ * n₃)))
      _ = _ := by
        simp only [w, Finset.mul_sum, mul_assoc]
  let R : (q : ℕ+) → ZMod (q : ℕ) → ℂ := fun q a =>
    ∑ m ∈ I, ∑ n₁ ∈ P₁, ∑ n₂ ∈ P₂, ∑ n₃ ∈ P₃,
      if ((m * n₁ * n₂ * n₃ : ℤ) : ZMod (q : ℕ)) = a then
        w m n₁ n₂ n₃ else 0
  let U : ℕ+ → ℂ := fun q =>
    ∑ m ∈ I, ∑ n₁ ∈ P₁, ∑ n₂ ∈ P₂, ∑ n₃ ∈ P₃,
      if IsUnit ((m * n₁ * n₂ * n₃ : ℤ) : ZMod (q : ℕ)) then
        w m n₁ n₂ n₃ else 0
  have hR (q : ℕ+) (a : ZMod (q : ℕ)) :
      (∑ n ∈ f.support, if (n : ZMod (q : ℕ)) = a then f n else 0) =
        R q a := by
    clear * - hpair
    simpa only [R, Int.cast_natCast, mul_ite, mul_one, mul_zero] using
      hpair (fun z => if (z : ZMod (q : ℕ)) = a then 1 else 0)
  have hU (q : ℕ+) :
      (∑ n ∈ f.support, if Nat.Coprime n (q : ℕ) then f n else 0) = U q := by
    clear * - hpair
    simpa only [U, Int.cast_natCast, ZMod.isUnit_iff_coprime,
      mul_ite, mul_one, mul_zero] using
      hpair (fun z => if IsUnit (z : ZMod (q : ℕ)) then 1 else 0)
  let a : ∀ q : ℕ+, (ZMod (q : ℕ))ˣ := fun q =>
    if hq : q ∈ Qset then (ha₀ q hq).unit else 1
  have ha : ∀ q ∈ Qset, (a q : ZMod (q : ℕ)) = (a₀ : ZMod (q : ℕ)) := by
    intro q hq
    simp only [a, dite_eq_left hq, IsUnit.unit_spec]
  have hsym (ψ : ℝ → ℂ) (hs : Function.support ψ ⊆ Set.Icc (1 / C) C) :
      Function.support ψ ⊆ Set.Icc (-C) C :=
    hs.trans (Set.Icc_subset_Icc_left
      ((neg_nonpos.mpr hCpos.le).trans (one_div_pos.mpr hCpos).le))
  have hper (j : ℕ) (hj : j ∈ Finset.range bins) :
      ∑ q ∈ Qset.filter (fun q => label q = j),
        ‖R q (a q : ZMod (q : ℕ)) - U q / ((q : ℕ).totient : ℂ)‖ ≤
      2 * Kp * (L₁ * L₂ * L₃) * Wα * ((C * M) * N) * x ^ (-2 * ε) := by
    have hh := hp x hxXp (C * M) N₁ N₂ N₃ (r ^ j)
      hMphys (hcenter j hj).1 hlarge₁ hlarge₂ hlarge₃
      hMNphyslo hMNphyshi hNlower (hcenter j hj).2 Y hY
      (Qset.filter (fun q => label q = j)) (hband j)
      M₀ M₁ hM₀ hwidth hheight L₁ L₂ L₃ Wα hL₁ hL₂ hL₃ hWα
      (fun m => α m.toNat) ψ₁ ψ₂ ψ₃ hαint hψ₁ hψ₂ hψ₃
      (hsym ψ₁ hs₁) (hsym ψ₂ hs₂) (hsym ψ₃ hs₃) hd₁ hd₂ hd₃
    exact hh.2 a₀ a (fun q hq => ha q (Finset.mem_filter.mp hq).1)
  clear * - hper hlabels hbins hR hU ha hMNphyshi hCpos hKp hAcov hKα
    hLα hL₁ hL₂ hL₃ hWα hM0 hN0 hx0 hlog0 hlogsmall hlogA
  let B : ℝ := 2 * Kp * Acov * Kα * C ^ 2 * (Lα * L₁ * L₂ * L₃)
  have hB : 0 ≤ B := by dsimp only [B]; positivity
  have hbulk : 0 ≤ 2 * Kp * (L₁ * L₂ * L₃) * Wα := by positivity
  have hcover : 0 ≤ Acov * x ^ ε * Real.log x := by positivity
  have hpower : x ^ ε * x ^ (ε / 4) * x * x ^ (-2 * ε) =
      x ^ (1 - 3 * ε / 4) := by
    clear * - hx0
    rw [← Real.rpow_add hx0, ← Real.rpow_add_one hx0.ne', ← Real.rpow_add hx0]
    congr 1
    ring
  change
    ∑ q ∈ Qset,
      ‖(∑ n ∈ f.support,
        if (n : ZMod (q : ℕ)) = (a₀ : ZMod (q : ℕ)) then f n else 0) -
        ((q : ℕ).totient : ℂ)⁻¹ *
          (∑ n ∈ f.support, if Nat.Coprime n (q : ℕ) then f n else 0)‖ ≤
      K * (Lα * L₁ * L₂ * L₃) * x / (Real.log x) ^ A
  calc
    _ = ∑ q ∈ Qset,
        ‖R q (a q : ZMod (q : ℕ)) - U q / ((q : ℕ).totient : ℂ)‖ := by
      apply Finset.sum_congr rfl
      intro q hq
      rw [hR, hU, ha q hq, div_eq_mul_inv, mul_comm (U q)]
    _ = ∑ j ∈ Finset.range bins, ∑ q ∈ Qset.filter (fun q => label q = j),
        ‖R q (a q : ZMod (q : ℕ)) - U q / ((q : ℕ).totient : ℂ)‖ :=
      (Finset.sum_fiberwise_of_maps_to hlabels _).symm
    _ ≤ (bins : ℝ) *
        (2 * Kp * (L₁ * L₂ * L₃) * Wα * ((C * M) * N) * x ^ (-2 * ε)) := by
      simpa only [Finset.sum_const, Finset.card_range, nsmul_eq_mul] using
        Finset.sum_le_sum hper
    _ ≤ (Acov * x ^ ε * Real.log x) *
        (2 * Kp * (L₁ * L₂ * L₃) * Wα * ((C * M) * N) * x ^ (-2 * ε)) :=
      mul_le_mul_of_nonneg_right hbins (by positivity)
    _ ≤ (Acov * x ^ ε * Real.log x) *
        (2 * Kp * (L₁ * L₂ * L₃) * Wα * (C ^ 2 * x) * x ^ (-2 * ε)) :=
      mul_le_mul_of_nonneg_left
        (mul_le_mul_of_nonneg_right
          (mul_le_mul_of_nonneg_left hMNphyshi hbulk)
          (Real.rpow_nonneg hx0.le _)) hcover
    _ = B * (x ^ ε * x ^ (ε / 4) * x * x ^ (-2 * ε)) * Real.log x := by
      dsimp only [B, Wα]
      ring
    _ = B * x ^ (1 - 3 * ε / 4) * Real.log x := by rw [hpower]
    _ ≤ B * x ^ (1 - 3 * ε / 4) * x ^ (ε / 4) :=
      mul_le_mul_of_nonneg_left hlogsmall (by positivity)
    _ = B * x ^ (1 - ε / 2) := by
      rw [mul_assoc, ← Real.rpow_add hx0]
      congr 1
      ring_nf
    _ ≤ B * x / (Real.log x) ^ A := by
      apply (le_div_iff₀ (Real.rpow_pos_of_pos hlog0 A)).mpr
      calc
        _ ≤ B * x ^ (1 - ε / 2) * x ^ (ε / 2) :=
          mul_le_mul_of_nonneg_left hlogA (by positivity)
        _ = B * x := by
          rw [mul_assoc, ← Real.rpow_add hx0]
          simp
    _ ≤ K * (Lα * L₁ * L₂ * L₃) * x / (Real.log x) ^ A := by
      apply div_le_div_of_nonneg_right _ (Real.rpow_nonneg hlog0.le _)
      apply mul_le_mul_of_nonneg_right _ hx0.le
      exact mul_le_mul_of_nonneg_right (le_add_of_nonneg_left zero_le_one) (by positivity)


#print axioms LocalFourierHypothesis.positive_smooth_convolution_global_log_saving

end

end PrimeGap182.TypeIII
