import TypeIIINonzeroFourier

/-!
# Actual sampled-convolution discrepancy on one modulus band

This is the exact public sampling, finite Taylor, periodization, and primitive
residue averaging proof, applied to the new checked nonzero Fourier estimate.
The only unproved input is the explicit local finite-field Fourier hypothesis.
Generated by scripts/build_type_iii_sampled_fineband.py.
-/

open scoped BigOperators Classical ContDiff NNReal
open PrimeGap186 PrimeGap182Audit UniqueFactorizationMonoid

namespace PrimeGap182.TypeIII

noncomputable section

set_option backward.isDefEq.respectTransparency false
set_option backward.isDefEq.respectTransparency.types false
set_option maxHeartbeats 4000000

theorem LocalFourierHypothesis.sampled_convolution_fineBand_discrepancy
    {C₀ : ℝ} (hC₀ : 0 ≤ C₀) {D₀ p₀ : ℕ} (hlocal : LocalFourierHypothesis C₀ D₀ p₀)
    (omegaExp δ σ C T E : ℝ)
    (hω : 0 < omegaExp) (hδ : 0 < δ) (hC : 1 ≤ C) (hT : 0 ≤ T)
    (hσupper : σ < 1 / 6)
    (hσ : 1 / 30 + 56 * omegaExp / 15 + 4 * δ / 15 < σ)
    (hswitch : 1 < 108 * omegaExp + 2 * δ) :
    let μ : ℝ := typeIIIMu σ
    let θ : ℝ := typeIIITheta omegaExp
    let εcap : ℝ := typeIIIEpsilonCap μ θ δ
    0 < εcap ∧
      ∀ ε : ℝ, 0 < ε → ε ≤ εcap →
      let J : ℕ := Nat.ceil (22 / ε)
      ∃ K X : ℝ, 0 < K ∧ Real.exp 1 ≤ X ∧
      ∀ x : ℝ, X ≤ x →
      ∀ M N₁ N₂ N₃ Qcenter : ℝ,
        1 ≤ M → 0 < Qcenter →
        8 * x ^ (ε / 2) ≤ N₁ →
        8 * x ^ (ε / 2) ≤ N₂ →
        8 * x ^ (ε / 2) ≤ N₃ →
        let N : ℝ := N₁ * N₂ * N₃
        x / C ≤ M * N → M * N ≤ C * x →
        x ^ (3 / 4 + 3 * σ / 2 - ε) / C ≤ N →
        Qcenter ≤ C * x ^ (1 / 2 + 2 * omegaExp + ε) →
      ∀ Y : Set.Ici (1 : ℝ), (Y : ℝ) = x ^ δ →
      ∀ Qset : Finset ℕ+,
        (∀ q ∈ Qset,
          Squarefree (q : ℕ) ∧
          Nonempty (DenseDivisibilityWitness Y 1 (q : ℕ)) ∧
          Qcenter * (1 - C * x ^ (-ε)) ≤ (q : ℝ) ∧
          (q : ℝ) ≤ Qcenter * (1 + C * x ^ (-ε))) →
      ∀ M₀ M₁ : ℤ, 0 < M₀ → (M₁ : ℝ) - (M₀ : ℝ) ≤ M →
        (∀ m ∈ Finset.Icc M₀ M₁, |(m : ℝ)| ≤ C * M) →
      ∀ (L₁ L₂ L₃ Wα : ℝ), 0 ≤ L₁ → 0 ≤ L₂ → 0 ≤ L₃ → 0 ≤ Wα →
      ∀ (α : ℤ → ℂ) (ψ₁ ψ₂ ψ₃ : ℝ → ℂ),
        (∀ m ∈ Finset.Icc M₀ M₁, ‖α m‖ ≤ Wα) →
        ContDiff ℝ ∞ ψ₁ → ContDiff ℝ ∞ ψ₂ → ContDiff ℝ ∞ ψ₃ →
        Function.support ψ₁ ⊆ Set.Icc (-T) T →
        Function.support ψ₂ ⊆ Set.Icc (-T) T →
        Function.support ψ₃ ⊆ Set.Icc (-T) T →
        (∀ r : ℕ, r ≤ J + 2 → ∀ t : ℝ,
          ‖iteratedDeriv r ψ₁ t‖ ≤ L₁ * (Real.log x) ^ E) →
        (∀ r : ℕ, r ≤ J + 2 → ∀ t : ℝ,
          ‖iteratedDeriv r ψ₂ t‖ ≤ L₂ * (Real.log x) ^ E) →
        (∀ r : ℕ, r ≤ J + 2 → ∀ t : ℝ,
          ‖iteratedDeriv r ψ₃ t‖ ≤ L₃ * (Real.log x) ^ E) →
        let I : Finset ℤ := Finset.Icc M₀ M₁
        let P₁ : Finset ℤ := Finset.Icc (Int.ceil (-T * N₁)) (Int.floor (T * N₁))
        let P₂ : Finset ℤ := Finset.Icc (Int.ceil (-T * N₂)) (Int.floor (T * N₂))
        let P₃ : Finset ℤ := Finset.Icc (Int.ceil (-T * N₃)) (Int.floor (T * N₃))
        let w : ℤ → ℤ → ℤ → ℤ → ℂ := fun m n₁ n₂ n₃ =>
          α m * ψ₁ ((n₁ : ℝ) / N₁) * ψ₂ ((n₂ : ℝ) / N₂) *
            ψ₃ ((n₃ : ℝ) / N₃)
        let R : (q : ℕ+) → ZMod (q : ℕ) → ℂ := fun q a =>
          ∑ m ∈ I, ∑ n₁ ∈ P₁, ∑ n₂ ∈ P₂, ∑ n₃ ∈ P₃,
            if ((m * n₁ * n₂ * n₃ : ℤ) : ZMod (q : ℕ)) = a then
              w m n₁ n₂ n₃ else 0
        let U : ℕ+ → ℂ := fun q =>
          ∑ m ∈ I, ∑ n₁ ∈ P₁, ∑ n₂ ∈ P₂, ∑ n₃ ∈ P₃,
            if IsUnit ((m * n₁ * n₂ * n₃ : ℤ) : ZMod (q : ℕ)) then
              w m n₁ n₂ n₃ else 0
        (∀ η : ℕ → ℂ, (∀ q ∈ Qset, ‖η (q : ℕ)‖ ≤ 1) →
          ∃ Z : ℂ,
          ∀ (a₀ : ℤ) (a : ∀ q : ℕ+, (ZMod (q : ℕ))ˣ),
            (∀ q ∈ Qset, (a q : ZMod (q : ℕ)) = (a₀ : ZMod (q : ℕ))) →
            ‖(∑ q ∈ Qset, η (q : ℕ) * R q (a q : ZMod (q : ℕ))) - Z‖ ≤
              K * (L₁ * L₂ * L₃) * Wα * (M * N) * x ^ (-2 * ε)) ∧
        (∀ (a₀ : ℤ) (a : ∀ q : ℕ+, (ZMod (q : ℕ))ˣ),
          (∀ q ∈ Qset, (a q : ZMod (q : ℕ)) = (a₀ : ZMod (q : ℕ))) →
          ∑ q ∈ Qset,
            ‖R q (a q : ZMod (q : ℕ)) - U q / ((q : ℕ).totient : ℂ)‖ ≤
            2 * K * (L₁ * L₂ * L₃) * Wα * (M * N) * x ^ (-2 * ε)) := by
  have hmarkCard (M : ℝ) (hM : 1 ≤ M) (M₀ M₁ : ℤ)
      (hwidth : (M₁ : ℝ) - (M₀ : ℝ) ≤ M) :
      ((Finset.Icc M₀ M₁).card : ℝ) ≤ 2 * M := by
    rcases (Finset.Icc M₀ M₁).eq_empty_or_nonempty with hI | hI
    · rw [hI, Finset.card_empty, Nat.cast_zero]
      linarith only [hM]
    · obtain ⟨m, hm⟩ := hI
      have hm' := Finset.mem_Icc.mp hm
      have hcast : ((Finset.Icc M₀ M₁).card : ℝ) =
          (M₁ : ℝ) + 1 - (M₀ : ℝ) := by
        exact_mod_cast Int.card_Icc_of_le M₀ M₁ (show M₀ ≤ M₁ + 1 by omega)
      rw [hcast]
      linarith only [hM, hwidth]
  have hωupper : omegaExp < 1 / 12 := by linarith only [hσupper, hσ, hδ]
  have hterm := hlocal.fineBand_nonzero_fourier_power_saving hC₀
    omegaExp δ σ C hω hδ hC hσupper hσ hswitch
  dsimp only at hterm ⊢
  refine ⟨hterm.1, ?_⟩
  intro ε hε hεcap
  let J : ℕ := Nat.ceil (22 / ε)
  have hεsmall : ε ≤ 1 / 100 := by
    have hh : ε ≤ 1 / 1000 := hεcap.trans (min_le_left _ _)
    linarith only [hh]
  obtain ⟨Kt, Xt, hKt, _, htermBound⟩ := hterm.2 ε hε hεcap
  have hft := typeIII_sampled_transform_fineBand_taylor (10 : ℝ) ε C T E
    (by norm_num) hε hC hT
  have horder : 2 * ((10 : ℝ) + 1) / ε = 22 / ε := by ring
  simp only [horder] at hft
  obtain ⟨Cf, Cerr, Xf, hCf, hCerr, _, hftBound⟩ := hft
  obtain ⟨Lstar, φ, hLstar, hφcont, hφnonneg, hφone, hφsupport, hφbounds⟩ :=
    exists_typeIII_smooth_majorant
  have hLstar0 : 0 ≤ Lstar := zero_le_one.trans hLstar
  obtain ⟨Xlog, _, hlogBound⟩ := typeIII_log_cube_threshold ε E hε
  have hfine : ∀ᶠ x : ℝ in Filter.atTop, C * x ^ (-ε) ≤ 1 / 3 := by
    have ht := (tendsto_rpow_neg_atTop hε).const_mul C
    exact ht.eventually_le_const (by norm_num : C * 0 < (1 : ℝ) / 3)
  obtain ⟨Xfine, hXfine⟩ := Filter.eventually_atTop.mp hfine
  let D : ℝ := 2 * T + 3
  let e : ℝ := 2 * Cerr
  let Dtel : ℝ := e * (D ^ 2 + (D + e) * D + (D + e) ^ 2)
  let Sstar : ℝ := Real.sqrt ((2 * (2 : ℝ) + 3) * Lstar)
  let Ct : ℝ := 8 * Kt * ((J + 1 : ℕ) : ℝ) ^ 3 * Cf ^ 3 * Sstar
  let Ce : ℝ := 8 * Dtel * C ^ 2
  let K : ℝ := 1 + Ct + Ce
  let X : ℝ := max (Real.exp 1) (max Xt (max Xf (max Xlog (max Xfine (2 * C)))))
  have hD : 0 ≤ D :=
    add_nonneg (mul_nonneg (by norm_num : (0 : ℝ) ≤ 2) hT) (by norm_num)
  have he : 0 ≤ e := mul_nonneg (by norm_num : (0 : ℝ) ≤ 2) hCerr.le
  have hDtel : 0 ≤ Dtel :=
    mul_nonneg he (add_nonneg
      (add_nonneg (sq_nonneg D) (mul_nonneg (add_nonneg hD he) hD))
      (sq_nonneg (D + e)))
  have hCt : 0 ≤ Ct :=
    mul_nonneg
      (mul_nonneg
        (mul_nonneg
          (mul_nonneg (by norm_num : (0 : ℝ) ≤ 8) hKt.le)
          (pow_nonneg (Nat.cast_nonneg (J + 1)) 3))
        (pow_nonneg hCf.le 3))
      (Real.sqrt_nonneg _)
  have hCe : 0 ≤ Ce :=
    mul_nonneg (mul_nonneg (by norm_num : (0 : ℝ) ≤ 8) hDtel) (sq_nonneg C)
  refine ⟨K, X, add_pos_of_pos_of_nonneg
    (add_pos_of_pos_of_nonneg zero_lt_one hCt) hCe, le_max_left _ _, ?_⟩
  intro x hx
  obtain ⟨hxexp, hxXt, hxXf, hxXlog, hxXfine, hxC⟩ :
      Real.exp 1 ≤ x ∧ Xt ≤ x ∧ Xf ≤ x ∧ Xlog ≤ x ∧ Xfine ≤ x ∧ 2 * C ≤ x := by
    simpa only [X, max_le_iff] using hx
  have hx1 : 1 ≤ x := (Real.one_le_exp (by norm_num : (0 : ℝ) ≤ 1)).trans hxexp
  have hx0 : 0 < x := zero_lt_one.trans_le hx1
  have hxlog : 1 ≤ Real.log x := by
    simpa only [Real.log_exp] using Real.log_le_log (Real.exp_pos 1) hxexp
  let ell : ℝ := (Real.log x) ^ E
  let A0 : ℝ := max 1 ell
  let t : ℝ := x ^ (-10 : ℝ)
  have hell : 0 < ell := Real.rpow_pos_of_pos (zero_lt_one.trans_le hxlog) E
  have hA0 : 1 ≤ A0 := le_max_left _ _
  have hA00 : 0 ≤ A0 := zero_le_one.trans hA0
  have hellA : ell ≤ A0 := le_max_right _ _
  have ht : 0 ≤ t := Real.rpow_nonneg hx0.le (-10)
  have hA03 : A0 ^ 3 ≤ x ^ ε := hlogBound x hxXlog
  have hell3 : ell ^ 3 ≤ x ^ ε := (pow_le_pow_left₀ hell.le hellA 3).trans hA03
  have hsmall : C * x ^ (-ε) ≤ 1 / 3 := hXfine x hxXfine
  have hr1 : 1 ≤ x ^ (ε / 2) :=
    Real.one_le_rpow hx1 (div_nonneg hε.le (by norm_num : (0 : ℝ) ≤ 2))
  intro M N₁ N₂ N₃ Qcenter hM hQ hN₁ hN₂ hN₃
  let N : ℝ := N₁ * N₂ * N₃
  have hN₁1 : 1 ≤ N₁ := by linarith only [hN₁, hr1]
  have hN₂1 : 1 ≤ N₂ := by linarith only [hN₂, hr1]
  have hN₃1 : 1 ≤ N₃ := by linarith only [hN₃, hr1]
  have hN₁0 : 0 < N₁ := zero_lt_one.trans_le hN₁1
  have hN₂0 : 0 < N₂ := zero_lt_one.trans_le hN₂1
  have hN₃0 : 0 < N₃ := zero_lt_one.trans_le hN₃1
  have hN0 : 0 < N := mul_pos (mul_pos hN₁0 hN₂0) hN₃0
  have hM0 : 0 ≤ M := zero_le_one.trans hM
  intro hMNlower hMNupper hNlower hQupper Y hY Qset hQset
  obtain ⟨hqtAll, hscaleError⟩ :=
    typeIII_fineband_scale_bounds omegaExp C E hωupper hC ε x Qcenter
      hε hεsmall hx1 hxC hQ hQupper hA03
  have hqUpper : ∀ q ∈ Qset, (q : ℝ) ≤ 2 * Qcenter := by
    intro q hq
    have hband := (hQset q hq).2.2.2
    nlinarith only [hband, hQ.le, mul_nonneg hQ.le (sub_nonneg.mpr hsmall)]
  have hqt : ∀ q ∈ Qset, (q : ℝ) * t ≤ 1 :=
    fun q hq => hqtAll q (hqUpper q hq)
  intro M₀ M₁ hM₀ hwidth hheight L₁ L₂ L₃ Wα hL₁ hL₂ hL₃ hWα
    α ψ₁ ψ₂ ψ₃ hα hψ₁ hψ₂ hψ₃ hsψ₁ hsψ₂ hsψ₃ hbψ₁ hbψ₂ hbψ₃
  let I : Finset ℤ := Finset.Icc M₀ M₁
  let P₁ : Finset ℤ := Finset.Icc (Int.ceil (-T * N₁)) (Int.floor (T * N₁))
  let P₂ : Finset ℤ := Finset.Icc (Int.ceil (-T * N₂)) (Int.floor (T * N₂))
  let P₃ : Finset ℤ := Finset.Icc (Int.ceil (-T * N₃)) (Int.floor (T * N₃))
  let w : ℤ → ℤ → ℤ → ℤ → ℂ := fun m n₁ n₂ n₃ =>
    α m * ψ₁ ((n₁ : ℝ) / N₁) * ψ₂ ((n₂ : ℝ) / N₂) * ψ₃ ((n₃ : ℝ) / N₃)
  let R : (q : ℕ+) → ZMod (q : ℕ) → ℂ := fun q a =>
    ∑ m ∈ I, ∑ n₁ ∈ P₁, ∑ n₂ ∈ P₂, ∑ n₃ ∈ P₃,
      if ((m * n₁ * n₂ * n₃ : ℤ) : ZMod (q : ℕ)) = a then w m n₁ n₂ n₃ else 0
  let U : ℕ+ → ℂ := fun q =>
    ∑ m ∈ I, ∑ n₁ ∈ P₁, ∑ n₂ ∈ P₂, ∑ n₃ ∈ P₃,
      if IsUnit ((m * n₁ * n₂ * n₃ : ℤ) : ZMod (q : ℕ)) then w m n₁ n₂ n₃ else 0
  let sampleTransform (NN : ℝ) (ψ : ℝ → ℂ) : ℝ → ℂ := fun y =>
    ∑ n ∈ Finset.Icc (Int.ceil (-T * NN)) (Int.floor (T * NN)),
      ψ ((n : ℝ) / NN) *
        Complex.exp (((-2 * Real.pi * (n : ℝ) * y : ℝ) : ℂ) * Complex.I)
  let coeff (NN : ℝ) (ψ : ℝ → ℂ) : ℕ → ℤ → ℂ := fun j h =>
    ((((h : ℝ) / Qcenter) ^ j / (Nat.factorial j : ℝ) / NN : ℝ) : ℂ) *
      iteratedDeriv j (sampleTransform NN ψ) ((h : ℝ) / Qcenter)
  let H (NN : ℝ) : ℝ := x ^ (ε / 2) * Qcenter / NN
  let S (NN : ℝ) : Finset ℤ := Finset.Icc (Int.ceil (-H NN)) (Int.floor (H NN))
  let theta : ℕ → ℕ → ℂ := fun q j =>
    ((Qcenter / (q : ℝ) * ((Qcenter - (q : ℝ)) / (q : ℝ)) ^ j : ℝ) : ℂ)
  let weight (NN : ℝ) (ψ : ℝ → ℂ) (q : ℕ+) : ZMod (q : ℕ) → ℂ :=
    integerIntervalResidueWeight (q : ℕ) (Int.ceil (-T * NN))
      (Int.floor (T * NN) + 1 - Int.ceil (-T * NN)).toNat
      (fun k => ψ (((Int.ceil (-T * NN) : ℝ) + (k : ℝ)) / NN))
  let approx (NN : ℝ) (ψ : ℝ → ℂ) (q : ℕ+) : ZMod (q : ℕ) → ℂ := fun z =>
    ((NN / Qcenter : ℝ) : ℂ) *
      ∑ j ∈ Finset.range (J + 1), theta (q : ℕ) j *
        ∑ h ∈ S NN, coeff NN ψ j h * ZMod.stdAddChar ((h : ZMod (q : ℕ)) * z)
  let Rt : (q : ℕ+) → ZMod (q : ℕ) → ℂ := fun q a =>
    ∑ m ∈ I, α m * ∑ z₁ : ZMod (q : ℕ), ∑ z₂ : ZMod (q : ℕ),
      ∑ z₃ : ZMod (q : ℕ),
        if (m : ZMod (q : ℕ)) * z₁ * z₂ * z₃ = a then
          approx N₁ ψ₁ q z₁ * approx N₂ ψ₂ q z₂ * approx N₃ ψ₃ q z₃ else 0
  let Bprod : ℝ := L₁ * L₂ * L₃
  have hBprod : 0 ≤ Bprod := mul_nonneg (mul_nonneg hL₁ hL₂) hL₃
  have hphysical (q : ℕ+) (a : ZMod (q : ℕ)) :
      R q a = ∑ m ∈ I, α m * ∑ z₁ : ZMod (q : ℕ),
        ∑ z₂ : ZMod (q : ℕ), ∑ z₃ : ZMod (q : ℕ),
          if (m : ZMod (q : ℕ)) * z₁ * z₂ * z₃ = a then
            weight N₁ ψ₁ q z₁ * weight N₂ ψ₂ q z₂ * weight N₃ ψ₃ q z₃ else 0 := by
    have hcastSample (NN : ℝ) (ψ : ℝ → ℂ) :
        (fun k : ℕ => ψ (((Int.ceil (-T * NN) + k : ℤ) : ℝ) / NN)) =
          (fun k : ℕ => ψ (((Int.ceil (-T * NN) : ℝ) + (k : ℝ)) / NN)) := by
      funext k
      rw [Int.cast_add, Int.cast_natCast]
    have hperiod :
        R q a = ∑ m ∈ I, α m * ∑ z₁ : ZMod (q : ℕ),
          ∑ z₂ : ZMod (q : ℕ), ∑ z₃ : ZMod (q : ℕ),
            if (m : ZMod (q : ℕ)) * z₁ * z₂ * z₃ = a then
              integerIntervalResidueWeight (q : ℕ) (Int.ceil (-T * N₁))
                  (Int.floor (T * N₁) + 1 - Int.ceil (-T * N₁)).toNat
                  (fun k => ψ₁ (((Int.ceil (-T * N₁) + k : ℤ) : ℝ) / N₁)) z₁ *
                integerIntervalResidueWeight (q : ℕ) (Int.ceil (-T * N₂))
                  (Int.floor (T * N₂) + 1 - Int.ceil (-T * N₂)).toNat
                  (fun k => ψ₂ (((Int.ceil (-T * N₂) + k : ℤ) : ℝ) / N₂)) z₂ *
                integerIntervalResidueWeight (q : ℕ) (Int.ceil (-T * N₃))
                  (Int.floor (T * N₃) + 1 - Int.ceil (-T * N₃)).toNat
                  (fun k => ψ₃ (((Int.ceil (-T * N₃) + k : ℤ) : ℝ) / N₃)) z₃
            else 0 :=
      typeIII_physical_periodization q I
        (Int.ceil (-T * N₁)) (Int.floor (T * N₁))
        (Int.ceil (-T * N₂)) (Int.floor (T * N₂))
        (Int.ceil (-T * N₃)) (Int.floor (T * N₃)) α
        (fun n => ψ₁ ((n : ℝ) / N₁)) (fun n => ψ₂ ((n : ℝ) / N₂))
        (fun n => ψ₃ ((n : ℝ) / N₃)) a
    rw [hcastSample N₁ ψ₁, hcastSample N₂ ψ₂, hcastSample N₃ ψ₃] at hperiod
    exact hperiod
  obtain ⟨hc₁, hrest₁⟩ := hftBound x hxXf L₁ hL₁ N₁ Qcenter hQ hN₁
    ψ₁ hψ₁ hsψ₁ hbψ₁
  obtain ⟨hc₂, hrest₂⟩ := hftBound x hxXf L₂ hL₂ N₂ Qcenter hQ hN₂
    ψ₂ hψ₂ hsψ₂ hbψ₂
  obtain ⟨hc₃, hrest₃⟩ := hftBound x hxXf L₃ hL₃ N₃ Qcenter hQ hN₃
    ψ₃ hψ₃ hsψ₃ hbψ₃
  have hcoef₁ : ∀ j : ℕ, j ≤ J → ∀ h ∈ S N₁,
      ‖coeff N₁ ψ₁ j h‖ ≤ Cf * L₁ * ell := hc₁
  have hcoef₂ : ∀ j : ℕ, j ≤ J → ∀ h ∈ S N₂,
      ‖coeff N₂ ψ₂ j h‖ ≤ Cf * L₂ * ell := hc₂
  have hcoef₃ : ∀ j : ℕ, j ≤ J → ∀ h ∈ S N₃,
      ‖coeff N₃ ψ₃ j h‖ ≤ Cf * L₃ * ell := hc₃
  have htheta : ∀ q ∈ Qset, ∀ j : ℕ, ‖theta (q : ℕ) j‖ ≤ 2 := by
    intro q hq j
    have hh := (hrest₁ q (hQset q hq).2.2.1 (hQset q hq).2.2.2).2.1 j
    simpa only [theta, Complex.norm_real, Real.norm_eq_abs] using hh
  have herr₁ : ∀ q ∈ Qset, ∀ z : ZMod (q : ℕ),
      ‖weight N₁ ψ₁ q z - approx N₁ ψ₁ q z‖ ≤ e * (L₁ * N₁) * t := by
    intro q hq z
    have hh := (hrest₁ q (hQset q hq).2.2.1 (hQset q hq).2.2.2).2.2.2.2.2.2 z
    convert hh using 1; try rfl
    dsimp only [e, t]
    ring
  have herr₂ : ∀ q ∈ Qset, ∀ z : ZMod (q : ℕ),
      ‖weight N₂ ψ₂ q z - approx N₂ ψ₂ q z‖ ≤ e * (L₂ * N₂) * t := by
    intro q hq z
    have hh := (hrest₂ q (hQset q hq).2.2.1 (hQset q hq).2.2.2).2.2.2.2.2.2 z
    convert hh using 1; try rfl
    dsimp only [e, t]
    ring
  have herr₃ : ∀ q ∈ Qset, ∀ z : ZMod (q : ℕ),
      ‖weight N₃ ψ₃ q z - approx N₃ ψ₃ q z‖ ≤ e * (L₃ * N₃) * t := by
    intro q hq z
    have hh := (hrest₃ q (hQset q hq).2.2.1 (hQset q hq).2.2.2).2.2.2.2.2.2 z
    convert hh using 1; try rfl
    dsimp only [e, t]
    ring
  have hW₁ : ∀ q ∈ Qset, (∑ z : ZMod (q : ℕ), ‖weight N₁ ψ₁ q z‖) ≤
      D * (L₁ * N₁) * A0 := by
    intro q _
    convert typeIII_sampled_residue_l1 q T N₁ L₁ A0 hT hN₁1 hL₁ hA00 ψ₁
      (fun u => by simpa only [iteratedDeriv_zero] using
        (hbψ₁ 0 (Nat.zero_le _) u).trans (mul_le_mul_of_nonneg_left hellA hL₁)) using 1;
      dsimp only [D]; ring
  have hW₂ : ∀ q ∈ Qset, (∑ z : ZMod (q : ℕ), ‖weight N₂ ψ₂ q z‖) ≤
      D * (L₂ * N₂) * A0 := by
    intro q _
    convert typeIII_sampled_residue_l1 q T N₂ L₂ A0 hT hN₂1 hL₂ hA00 ψ₂
      (fun u => by simpa only [iteratedDeriv_zero] using
        (hbψ₂ 0 (Nat.zero_le _) u).trans (mul_le_mul_of_nonneg_left hellA hL₂)) using 1;
      dsimp only [D]; ring
  have hW₃ : ∀ q ∈ Qset, (∑ z : ZMod (q : ℕ), ‖weight N₃ ψ₃ q z‖) ≤
      D * (L₃ * N₃) * A0 := by
    intro q _
    convert typeIII_sampled_residue_l1 q T N₃ L₃ A0 hT hN₃1 hL₃ hA00 ψ₃
      (fun u => by simpa only [iteratedDeriv_zero] using
        (hbψ₃ 0 (Nat.zero_le _) u).trans (mul_le_mul_of_nonneg_left hellA hL₃)) using 1;
      dsimp only [D]; ring
  have herror (η : ℕ → ℂ) (hη : ∀ q ∈ Qset, ‖η (q : ℕ)‖ ≤ 1)
      (a : ∀ q : ℕ+, (ZMod (q : ℕ))ˣ) :
      ‖(∑ q ∈ Qset, η (q : ℕ) * R q (a q : ZMod (q : ℕ))) -
        (∑ q ∈ Qset, η (q : ℕ) * Rt q (a q : ZMod (q : ℕ)))‖ ≤
        Ce * Bprod * Wα * (M * N) * x ^ (-2 * ε) := by
    have hraw := typeIII_weighted_physical_error Qset Qcenter hQ hqUpper I M Wα
      hM0 hWα (hmarkCard M hM M₀ M₁ hwidth) α hα
      D e A0 t (L₁ * N₁) (L₂ * N₂) (L₃ * N₃)
      hD he hA0 ht (mul_nonneg hL₁ hN₁0.le)
      (mul_nonneg hL₂ hN₂0.le) (mul_nonneg hL₃ hN₃0.le) hqt
      (weight N₁ ψ₁) (weight N₂ ψ₂) (weight N₃ ψ₃)
      (approx N₁ ψ₁) (approx N₂ ψ₂) (approx N₃ ψ₃)
      hW₁ hW₂ hW₃ herr₁ herr₂ herr₃ η hη
      (fun q => (a q : ZMod (q : ℕ)))
    calc
      _ ≤ 8 * Dtel * Wα * M * ((L₁ * N₁) * (L₂ * N₂) * (L₃ * N₃)) *
          Qcenter ^ 2 * A0 ^ 2 * t := by
        simpa only [← hphysical] using hraw
      _ = (8 * Dtel * Bprod * Wα * (M * N)) *
          (Qcenter ^ 2 * A0 ^ 2 * t) := by dsimp only [Bprod, N]; ring
      _ ≤ (8 * Dtel * Bprod * Wα * (M * N)) * (C ^ 2 * x ^ (-2 * ε)) :=
        mul_le_mul_of_nonneg_left hscaleError
          (mul_nonneg
            (mul_nonneg
              (mul_nonneg (mul_nonneg (by norm_num : (0 : ℝ) ≤ 8) hDtel) hBprod)
              hWα)
            (mul_nonneg hM0 hN0.le))
      _ = _ := by dsimp only [Ce]; ring
  have htripleSumNorm (f : ℕ → ℕ → ℕ → ℂ) (B : ℝ)
      (hb : ∀ j₁ ∈ Finset.range (J + 1), ∀ j₂ ∈ Finset.range (J + 1),
        ∀ j₃ ∈ Finset.range (J + 1), ‖f j₁ j₂ j₃‖ ≤ B) :
      ‖∑ j₁ ∈ Finset.range (J + 1), ∑ j₂ ∈ Finset.range (J + 1),
        ∑ j₃ ∈ Finset.range (J + 1), f j₁ j₂ j₃‖ ≤
        ((J + 1 : ℕ) : ℝ) ^ 3 * B := by
    calc
      _ ≤ ∑ j₁ ∈ Finset.range (J + 1), ∑ j₂ ∈ Finset.range (J + 1),
          ∑ j₃ ∈ Finset.range (J + 1), B :=
        norm_sum_le_of_le _ fun j₁ hj₁ =>
          norm_sum_le_of_le _ fun j₂ hj₂ =>
            norm_sum_le_of_le _ fun j₃ hj₃ => hb j₁ hj₁ j₂ hj₂ j₃ hj₃
      _ = _ := by
        simp only [Finset.sum_const, Finset.card_range, nsmul_eq_mul]
        ring
  have hlogSaving : ell ^ 3 * x ^ (-3 * ε) ≤ x ^ (-2 * ε) := by
    calc
      _ ≤ x ^ ε * x ^ (-3 * ε) :=
        mul_le_mul_of_nonneg_right hell3 (Real.rpow_nonneg hx0.le (-3 * ε))
      _ = _ := by rw [← Real.rpow_add hx0]; congr 1; ring
  let kappa : ℂ := ((N₁ / Qcenter : ℝ) : ℂ) * ((N₂ / Qcenter : ℝ) : ℂ) *
    ((N₃ / Qcenter : ℝ) : ℂ)
  have hkappa : kappa = ((N / Qcenter ^ 3 : ℝ) : ℂ) := by
    dsimp only [kappa, N]
    push_cast
    have hQcomplex : (Qcenter : ℂ) ≠ 0 := by exact_mod_cast hQ.ne'
    field_simp
  let Sbox : Finset (ℤ × ℤ × ℤ) := (S N₁) ×ˢ ((S N₂) ×ˢ (S N₃))
  let Szero : Finset (ℤ × ℤ × ℤ) := Sbox.filter (fun h => h.1 * h.2.1 * h.2.2 = 0)
  let Snz : Finset (ℤ × ℤ × ℤ) := Sbox.filter (fun h => h.1 * h.2.1 * h.2.2 ≠ 0)
  let cTriple (j₁ j₂ j₃ : ℕ) (h : ℤ × ℤ × ℤ) : ℂ :=
    coeff N₁ ψ₁ j₁ h.1 * coeff N₂ ψ₂ j₂ h.2.1 * coeff N₃ ψ₃ j₃ h.2.2
  have hcoeffTriple (j₁ j₂ j₃ : ℕ)
      (hj₁ : j₁ ∈ Finset.range (J + 1)) (hj₂ : j₂ ∈ Finset.range (J + 1))
      (hj₃ : j₃ ∈ Finset.range (J + 1)) :
      ∀ h ∈ Snz, ‖cTriple j₁ j₂ j₃ h‖ ≤ Cf ^ 3 * Bprod * ell ^ 3 := by
    intro h hh
    have hbox := (Finset.mem_filter.mp hh).1
    obtain ⟨hh₁, hh₂₃⟩ := Finset.mem_product.mp hbox
    obtain ⟨hh₂, hh₃⟩ := Finset.mem_product.mp hh₂₃
    have hj₁' : j₁ ≤ J := by simpa only [Finset.mem_range, Nat.lt_succ_iff] using hj₁
    have hj₂' : j₂ ≤ J := by simpa only [Finset.mem_range, Nat.lt_succ_iff] using hj₂
    have hj₃' : j₃ ≤ J := by simpa only [Finset.mem_range, Nat.lt_succ_iff] using hj₃
    calc
      _ ≤ (Cf * L₁ * ell) * (Cf * L₂ * ell) * (Cf * L₃ * ell) :=
        norm_mul_le_of_le
          (norm_mul_le_of_le (hcoef₁ j₁ hj₁' h.1 hh₁) (hcoef₂ j₂ hj₂' h.2.1 hh₂))
          (hcoef₃ j₃ hj₃' h.2.2 hh₃)
      _ = _ := by dsimp only [Bprod]; ring
  have hcenter :
      ∀ η : ℕ → ℂ, (∀ q ∈ Qset, ‖η (q : ℕ)‖ ≤ 1) →
        ∃ Z : ℂ,
        ∀ (a₀ : ℤ) (a : ∀ q : ℕ+, (ZMod (q : ℕ))ˣ),
          (∀ q ∈ Qset, (a q : ZMod (q : ℕ)) = (a₀ : ZMod (q : ℕ))) →
          ‖(∑ q ∈ Qset, η (q : ℕ) * R q (a q : ZMod (q : ℕ))) - Z‖ ≤
            K * Bprod * Wα * (M * N) * x ^ (-2 * ε) := by
    intro η hη
    let etaTriple (j₁ j₂ j₃ : ℕ) (q : ℕ) : ℂ :=
      η q * theta q j₁ * theta q j₂ * theta q j₃
    let V (j₁ j₂ j₃ : ℕ) (a : ∀ q : ℕ+, (ZMod (q : ℕ))ˣ) : ℂ :=
      kappa * ∑ q ∈ Qset, (q : ℂ) * etaTriple j₁ j₂ j₃ (q : ℕ) *
        ∑ m ∈ I, if hm : IsUnit (m : ZMod (q : ℕ)) then
          α m * ∑ h ∈ Snz, cTriple j₁ j₂ j₃ h *
            typeIIICompleteFiberSum (q : ℕ)
              (h.1 : ZMod (q : ℕ)) (h.2.1 : ZMod (q : ℕ))
              (h.2.2 : ZMod (q : ℕ)) (a q * hm.unit⁻¹)
        else 0
    let Z : ℂ := kappa *
      ∑ j₁ ∈ Finset.range (J + 1), ∑ j₂ ∈ Finset.range (J + 1),
        ∑ j₃ ∈ Finset.range (J + 1),
          ∑ q ∈ Qset, (q : ℂ) * etaTriple j₁ j₂ j₃ (q : ℕ) *
            ∑ m ∈ I, if IsUnit (m : ZMod (q : ℕ)) then
              α m * ∑ h ∈ Szero, cTriple j₁ j₂ j₃ h *
                typeIIICompleteFiberSum (q : ℕ)
                  (h.1 : ZMod (q : ℕ)) (h.2.1 : ZMod (q : ℕ))
                  (h.2.2 : ZMod (q : ℕ)) 1
            else 0
    refine ⟨Z, ?_⟩
    intro a₀ a ha
    have hdecomposition :
        (∑ q ∈ Qset, η (q : ℕ) * Rt q (a q : ZMod (q : ℕ))) - Z =
          ∑ j₁ ∈ Finset.range (J + 1), ∑ j₂ ∈ Finset.range (J + 1),
            ∑ j₃ ∈ Finset.range (J + 1), V j₁ j₂ j₃ a :=
      typeIII_global_taylor_zero_nonzero_decomposition Qset I
        (Finset.range (J + 1)) (S N₁) (S N₂) (S N₃) α η theta
        (coeff N₁ ψ₁) (coeff N₂ ψ₂) (coeff N₃ ψ₃)
        ((N₁ / Qcenter : ℝ) : ℂ) ((N₂ / Qcenter : ℝ) : ℂ)
        ((N₃ / Qcenter : ℝ) : ℂ) a
    have hetaTriple (j₁ j₂ j₃ : ℕ) :
        ∀ q ∈ Qset, ‖etaTriple j₁ j₂ j₃ (q : ℕ)‖ ≤ 8 := by
      intro q hq
      calc
        _ ≤ 1 * 2 * 2 * (2 : ℝ) :=
          norm_mul_le_of_le
            (norm_mul_le_of_le (norm_mul_le_of_le (hη q hq) (htheta q hq j₁))
              (htheta q hq j₂))
            (htheta q hq j₃)
        _ = 8 := by norm_num
    have hVbound (j₁ j₂ j₃ : ℕ)
        (hj₁ : j₁ ∈ Finset.range (J + 1)) (hj₂ : j₂ ∈ Finset.range (J + 1))
        (hj₃ : j₃ ∈ Finset.range (J + 1)) :
        ‖V j₁ j₂ j₃ a‖ ≤
          Kt * (Cf ^ 3 * Bprod * ell ^ 3) * 8 * Wα * Sstar *
            (M * N) * x ^ (-3 * ε) := by
      dsimp only [V]
      rw [hkappa]
      exact htermBound x hxXt M N₁ N₂ N₃ Qcenter
        hM hN₁1 hN₂1 hN₃1 hQ hMNlower hMNupper hNlower hQupper
        Y hY Qset hQset a₀ a ha M₀ M₁ hM₀ hwidth hheight
        (etaTriple j₁ j₂ j₃) α (cTriple j₁ j₂ j₃)
        8 Wα (Cf ^ 3 * Bprod * ell ^ 3)
        (by norm_num) hWα
        (mul_nonneg (mul_nonneg (pow_nonneg hCf.le 3) hBprod) (pow_nonneg hell.le 3))
        (hetaTriple j₁ j₂ j₃) hα (hcoeffTriple j₁ j₂ j₃ hj₁ hj₂ hj₃)
        2 Lstar φ (by norm_num) hLstar0 hφcont hφnonneg hφone hφsupport hφbounds
    have hVsum :
        ‖∑ j₁ ∈ Finset.range (J + 1), ∑ j₂ ∈ Finset.range (J + 1),
          ∑ j₃ ∈ Finset.range (J + 1), V j₁ j₂ j₃ a‖ ≤
          Ct * Bprod * Wα * (M * N) * x ^ (-2 * ε) := by
      calc
        _ ≤ ((J + 1 : ℕ) : ℝ) ^ 3 *
            (Kt * (Cf ^ 3 * Bprod * ell ^ 3) * 8 * Wα * Sstar *
              (M * N) * x ^ (-3 * ε)) :=
          htripleSumNorm (fun j₁ j₂ j₃ => V j₁ j₂ j₃ a) _
            (fun j₁ hj₁ j₂ hj₂ j₃ hj₃ => hVbound j₁ j₂ j₃ hj₁ hj₂ hj₃)
        _ = (Ct * Bprod * Wα * (M * N)) * (ell ^ 3 * x ^ (-3 * ε)) := by
          dsimp only [Ct]
          ring
        _ ≤ (Ct * Bprod * Wα * (M * N)) * x ^ (-2 * ε) :=
          mul_le_mul_of_nonneg_left hlogSaving
            (mul_nonneg (mul_nonneg (mul_nonneg hCt hBprod) hWα)
              (mul_nonneg hM0 hN0.le))
        _ = _ := by ring
    calc
      _ ≤ ‖(∑ q ∈ Qset, η (q : ℕ) * R q (a q : ZMod (q : ℕ))) -
            (∑ q ∈ Qset, η (q : ℕ) * Rt q (a q : ZMod (q : ℕ)))‖ +
          ‖(∑ q ∈ Qset, η (q : ℕ) * Rt q (a q : ZMod (q : ℕ))) - Z‖ :=
        norm_sub_le_norm_sub_add_norm_sub _ _ _
      _ ≤ Ce * Bprod * Wα * (M * N) * x ^ (-2 * ε) +
          Ct * Bprod * Wα * (M * N) * x ^ (-2 * ε) := by
        apply add_le_add (herror η hη a)
        rw [hdecomposition]
        exact hVsum
      _ = (Ce + Ct) * (Bprod * Wα * (M * N) * x ^ (-2 * ε)) := by ring
      _ ≤ K * (Bprod * Wα * (M * N) * x ^ (-2 * ε)) :=
        mul_le_mul_of_nonneg_right (by dsimp only [K]; linarith only [])
          (mul_nonneg (mul_nonneg (mul_nonneg hBprod hWα) (mul_nonneg hM0 hN0.le))
            (Real.rpow_nonneg hx0.le (-2 * ε)))
      _ = _ := by ring
  refine ⟨hcenter, ?_⟩
  intro a₀ a ha
  have hnorm :
      (∑ q ∈ Qset,
        ‖R q (a q : ZMod (q : ℕ)) - U q / ((q : ℕ).totient : ℂ)‖) ≤
          2 * (K * Bprod * Wα * (M * N) * x ^ (-2 * ε)) :=
    typeIII_physical_coherent_center_to_norm Qset I P₁ P₂ P₃ w
      (K * Bprod * Wα * (M * N) * x ^ (-2 * ε)) hcenter a₀ a ha
  calc
    _ ≤ 2 * (K * Bprod * Wα * (M * N) * x ^ (-2 * ε)) := hnorm
    _ = _ := by dsimp only [Bprod]; ring


#print axioms LocalFourierHypothesis.sampled_convolution_fineBand_discrepancy

end

end PrimeGap182.TypeIII
